-- AUTO-GENERATED by tools/build_alchemy.py. DO NOT EDIT BY HAND.
-- Classic (1-300) alchemy recipes: crafted item name -> { skill, reagents={ {name,count},... } }.
-- Used by DropChanceTooltip material aggregation (potion/elixir -> "Alchemy <skill>").
DropChanceTooltip_AlchemyRecipes = {
    ["Arcane Elixir"] = { skill = 235, reagents = { {"Blindweed",1}, {"Goldthorn",1}, {"Crystal Vial",1} } },  -- item 9155
    ["Blackmouth Oil"] = { skill = 80, reagents = { {"Oily Blackmouth",1}, {"Empty Vial",1} } },  -- item 6370
    ["Catseye Elixir"] = { skill = 200, reagents = { {"Goldthorn",1}, {"Fadeleaf",1}, {"Leaded Vial",1} } },  -- item 10592
    ["Dreamless Sleep Potion"] = { skill = 230, reagents = { {"Purple Lotus",1}, {"Crystal Vial",1} } },  -- item 12190
    ["Elixir of Agility"] = { skill = 185, reagents = { {"Stranglekelp",1}, {"Goldthorn",1}, {"Leaded Vial",1} } },  -- item 8949
    ["Elixir of Brute Force"] = { skill = 275, reagents = { {"Gromsblood",1}, {"Plaguebloom",1}, {"Crystal Vial",1} } },  -- item 13453
    ["Elixir of Defense"] = { skill = 130, reagents = { {"Wild Steelbloom",1}, {"Stranglekelp",1}, {"Leaded Vial",1} } },  -- item 3389
    ["Elixir of Demonslaying"] = { skill = 250, reagents = { {"Gromsblood",1}, {"Ghost Mushroom",1}, {"Crystal Vial",1} } },  -- item 9224
    ["Elixir of Detect Demon"] = { skill = 250, reagents = { {"Gromsblood",1}, {"Crystal Vial",1} } },  -- item 9233
    ["Elixir of Detect Lesser Invisibility"] = { skill = 195, reagents = { {"Khadgar's Whisker",1}, {"Fadeleaf",1}, {"Leaded Vial",1} } },  -- item 3828
    ["Elixir of Detect Undead"] = { skill = 230, reagents = { {"Arthas' Tears",1}, {"Crystal Vial",1} } },  -- item 9154
    ["Elixir of Dream Vision"] = { skill = 240, reagents = { {"Purple Lotus",1}, {"Crystal Vial",1} } },  -- item 9197
    ["Elixir of Firepower"] = { skill = 140, reagents = { {"Fire Oil",1}, {"Kingsblood",1}, {"Leaded Vial",1} } },  -- item 6373
    ["Elixir of Fortitude"] = { skill = 175, reagents = { {"Wild Steelbloom",1}, {"Goldthorn",1}, {"Leaded Vial",1} } },  -- item 3825
    ["Elixir of Frost Power"] = { skill = 190, reagents = { {"Wintersbite",1}, {"Khadgar's Whisker",1}, {"Leaded Vial",1} } },  -- item 17708
    ["Elixir of Giant Growth"] = { skill = 90, reagents = { {"Deviate Fish",1}, {"Earthroot",1}, {"Empty Vial",1} } },  -- item 6662
    ["Elixir of Giants"] = { skill = 245, reagents = { {"Sungrass",1}, {"Gromsblood",1}, {"Crystal Vial",1} } },  -- item 9206
    ["Elixir of Greater Agility"] = { skill = 240, reagents = { {"Sungrass",1}, {"Goldthorn",1}, {"Crystal Vial",1} } },  -- item 9187
    ["Elixir of Greater Defense"] = { skill = 195, reagents = { {"Wild Steelbloom",1}, {"Goldthorn",1}, {"Leaded Vial",1} } },  -- item 8951
    ["Elixir of Greater Firepower"] = { skill = 250, reagents = { {"Fire Oil",1}, {"Firebloom",1}, {"Crystal Vial",1} } },  -- item 21546
    ["Elixir of Greater Intellect"] = { skill = 235, reagents = { {"Blindweed",1}, {"Khadgar's Whisker",1}, {"Crystal Vial",1} } },  -- item 9179
    ["Elixir of Greater Water Breathing"] = { skill = 215, reagents = { {"Ichor of Undeath",1}, {"Purple Lotus",1}, {"Crystal Vial",1} } },  -- item 18294
    ["Elixir of Lesser Agility"] = { skill = 140, reagents = { {"Wild Steelbloom",1}, {"Swiftthistle",1}, {"Leaded Vial",1} } },  -- item 3390
    ["Elixir of Lion's Strength"] = { skill = 1, reagents = { {"Earthroot",1}, {"Silverleaf",1}, {"Empty Vial",1} } },  -- item 2454
    ["Elixir of Minor Agility"] = { skill = 50, reagents = { {"Swiftthistle",1}, {"Silverleaf",1}, {"Empty Vial",1} } },  -- item 2457
    ["Elixir of Minor Defense"] = { skill = 1, reagents = { {"Silverleaf",1}, {"Empty Vial",1} } },  -- item 5997
    ["Elixir of Minor Fortitude"] = { skill = 50, reagents = { {"Earthroot",1}, {"Peacebloom",1}, {"Empty Vial",1} } },  -- item 2458
    ["Elixir of Ogre's Strength"] = { skill = 150, reagents = { {"Earthroot",1}, {"Kingsblood",1}, {"Leaded Vial",1} } },  -- item 3391
    ["Elixir of Poison Resistance"] = { skill = 120, reagents = { {"Large Venom Sac",1}, {"Bruiseweed",1}, {"Leaded Vial",1} } },  -- item 3386
    ["Elixir of Shadow Power"] = { skill = 250, reagents = { {"Ghost Mushroom",1}, {"Crystal Vial",1} } },  -- item 9264
    ["Elixir of Superior Defense"] = { skill = 265, reagents = { {"Stonescale Oil",1}, {"Sungrass",1}, {"Crystal Vial",1} } },  -- item 13445
    ["Elixir of the Mongoose"] = { skill = 280, reagents = { {"Mountain Silversage",1}, {"Plaguebloom",1}, {"Crystal Vial",1} } },  -- item 13452
    ["Elixir of the Sages"] = { skill = 270, reagents = { {"Dreamfoil",1}, {"Plaguebloom",1}, {"Crystal Vial",1} } },  -- item 13447
    ["Elixir of Water Breathing"] = { skill = 90, reagents = { {"Stranglekelp",1}, {"Blackmouth Oil",1}, {"Empty Vial",1} } },  -- item 5996
    ["Elixir of Wisdom"] = { skill = 90, reagents = { {"Mageroyal",1}, {"Briarthorn",1}, {"Empty Vial",1} } },  -- item 3383
    ["Fire Oil"] = { skill = 130, reagents = { {"Firefin Snapper",1}, {"Empty Vial",1} } },  -- item 6371
    ["Fire Protection Potion"] = { skill = 165, reagents = { {"Small Flame Sac",1}, {"Fire Oil",1}, {"Leaded Vial",1} } },  -- item 6049
    ["Flask of Chromatic Resistance"] = { skill = 300, reagents = { {"Icecap",1}, {"Mountain Silversage",1}, {"Black Lotus",1}, {"Crystal Vial",1} } },  -- item 13513
    ["Flask of Distilled Wisdom"] = { skill = 300, reagents = { {"Dreamfoil",1}, {"Icecap",1}, {"Black Lotus",1}, {"Crystal Vial",1} } },  -- item 13511
    ["Flask of Petrification"] = { skill = 300, reagents = { {"Stonescale Oil",1}, {"Mountain Silversage",1}, {"Black Lotus",1}, {"Crystal Vial",1} } },  -- item 13506
    ["Flask of Supreme Power"] = { skill = 300, reagents = { {"Dreamfoil",1}, {"Mountain Silversage",1}, {"Black Lotus",1}, {"Crystal Vial",1} } },  -- item 13512
    ["Flask of the Titans"] = { skill = 300, reagents = { {"Gromsblood",1}, {"Stonescale Oil",1}, {"Black Lotus",1}, {"Crystal Vial",1} } },  -- item 13510
    ["Free Action Potion"] = { skill = 150, reagents = { {"Blackmouth Oil",1}, {"Stranglekelp",1}, {"Leaded Vial",1} } },  -- item 5634
    ["Frost Oil"] = { skill = 200, reagents = { {"Khadgar's Whisker",1}, {"Wintersbite",1}, {"Leaded Vial",1} } },  -- item 3829
    ["Frost Protection Potion"] = { skill = 190, reagents = { {"Wintersbite",1}, {"Goldthorn",1}, {"Leaded Vial",1} } },  -- item 6050
    ["Ghost Dye"] = { skill = 245, reagents = { {"Ghost Mushroom",1}, {"Purple Dye",1}, {"Crystal Vial",1} } },  -- item 9210
    ["Gift of Arthas"] = { skill = 240, reagents = { {"Arthas' Tears",1}, {"Blindweed",1}, {"Crystal Vial",1} } },  -- item 9088
    ["Goblin Rocket Fuel"] = { skill = 210, reagents = { {"Firebloom",1}, {"Volatile Rum",1}, {"Leaded Vial",1} } },  -- item 9061
    ["Great Rage Potion"] = { skill = 175, reagents = { {"Large Fang",1}, {"Kingsblood",1}, {"Leaded Vial",1} } },  -- item 5633
    ["Greater Arcane Elixir"] = { skill = 285, reagents = { {"Dreamfoil",1}, {"Mountain Silversage",1}, {"Crystal Vial",1} } },  -- item 13454
    ["Greater Arcane Protection Potion"] = { skill = 290, reagents = { {"Dream Dust",1}, {"Dreamfoil",1}, {"Crystal Vial",1} } },  -- item 13461
    ["Greater Dreamless Sleep Potion"] = { skill = 275, reagents = { {"Dreamfoil",1}, {"Golden Sansam",1}, {"Crystal Vial",1} } },  -- item 20002
    ["Greater Fire Protection Potion"] = { skill = 290, reagents = { {"Elemental Fire",1}, {"Dreamfoil",1}, {"Crystal Vial",1} } },  -- item 13457
    ["Greater Frost Protection Potion"] = { skill = 290, reagents = { {"Elemental Water",1}, {"Dreamfoil",1}, {"Crystal Vial",1} } },  -- item 13456
    ["Greater Healing Potion"] = { skill = 155, reagents = { {"Liferoot",1}, {"Kingsblood",1}, {"Leaded Vial",1} } },  -- item 1710
    ["Greater Mana Potion"] = { skill = 205, reagents = { {"Khadgar's Whisker",1}, {"Goldthorn",1}, {"Leaded Vial",1} } },  -- item 6149
    ["Greater Nature Protection Potion"] = { skill = 290, reagents = { {"Elemental Earth",1}, {"Dreamfoil",1}, {"Crystal Vial",1} } },  -- item 13458
    ["Greater Shadow Protection Potion"] = { skill = 290, reagents = { {"Shadow Oil",1}, {"Dreamfoil",1}, {"Crystal Vial",1} } },  -- item 13459
    ["Greater Stoneshield Potion"] = { skill = 280, reagents = { {"Stonescale Oil",1}, {"Thorium Ore",1}, {"Crystal Vial",1} } },  -- item 13455
    ["Healing Potion"] = { skill = 110, reagents = { {"Bruiseweed",1}, {"Briarthorn",1}, {"Leaded Vial",1} } },  -- item 929
    ["Holy Protection Potion"] = { skill = 100, reagents = { {"Bruiseweed",1}, {"Swiftthistle",1}, {"Empty Vial",1} } },  -- item 6051
    ["Invisibility Potion"] = { skill = 235, reagents = { {"Ghost Mushroom",1}, {"Sungrass",1}, {"Crystal Vial",1} } },  -- item 9172
    ["Lesser Healing Potion"] = { skill = 55, reagents = { {"Minor Healing Potion",1}, {"Briarthorn",1} } },  -- item 858
    ["Lesser Invisibility Potion"] = { skill = 165, reagents = { {"Fadeleaf",1}, {"Wild Steelbloom",1}, {"Leaded Vial",1} } },  -- item 3823
    ["Lesser Mana Potion"] = { skill = 120, reagents = { {"Mageroyal",1}, {"Stranglekelp",1}, {"Empty Vial",1} } },  -- item 3385
    ["Lesser Stoneshield Potion"] = { skill = 215, reagents = { {"Mithril Ore",1}, {"Goldthorn",1}, {"Leaded Vial",1} } },  -- item 4623
    ["Limited Invulnerability Potion"] = { skill = 250, reagents = { {"Blindweed",1}, {"Ghost Mushroom",1}, {"Crystal Vial",1} } },  -- item 3387
    ["Living Action Potion"] = { skill = 285, reagents = { {"Icecap",1}, {"Mountain Silversage",1}, {"Heart of the Wild",1}, {"Crystal Vial",1} } },  -- item 20008
    ["Mageblood Potion"] = { skill = 275, reagents = { {"Dreamfoil",1}, {"Plaguebloom",1}, {"Crystal Vial",1} } },  -- item 20007
    ["Magic Resistance Potion"] = { skill = 210, reagents = { {"Khadgar's Whisker",1}, {"Purple Lotus",1}, {"Crystal Vial",1} } },  -- item 9036
    ["Major Healing Potion"] = { skill = 275, reagents = { {"Golden Sansam",2}, {"Mountain Silversage",1}, {"Crystal Vial",1} } },  -- item 13446
    ["Major Mana Potion"] = { skill = 295, reagents = { {"Dreamfoil",1}, {"Icecap",1}, {"Crystal Vial",1} } },  -- item 13444
    ["Major Rejuvenation Potion"] = { skill = 300, reagents = { {"Heart of the Wild",1}, {"Golden Sansam",1}, {"Dreamfoil",1}, {"Imbued Vial",1} } },  -- item 18253
    ["Major Troll's Blood Potion"] = { skill = 290, reagents = { {"Gromsblood",1}, {"Plaguebloom",1}, {"Crystal Vial",1} } },  -- item 20004
    ["Mana Potion"] = { skill = 160, reagents = { {"Stranglekelp",1}, {"Kingsblood",1}, {"Leaded Vial",1} } },  -- item 3827
    ["Mighty Rage Potion"] = { skill = 255, reagents = { {"Gromsblood",1}, {"Crystal Vial",1} } },  -- item 13442
    ["Mighty Troll's Blood Potion"] = { skill = 180, reagents = { {"Liferoot",1}, {"Bruiseweed",1}, {"Leaded Vial",1} } },  -- item 3826
    ["Minor Healing Potion"] = { skill = 1, reagents = { {"Peacebloom",1}, {"Silverleaf",1}, {"Empty Vial",1} } },  -- item 118
    ["Minor Magic Resistance Potion"] = { skill = 110, reagents = { {"Mageroyal",1}, {"Wild Steelbloom",1}, {"Empty Vial",1} } },  -- item 3384
    ["Minor Mana Potion"] = { skill = 25, reagents = { {"Mageroyal",1}, {"Silverleaf",1}, {"Empty Vial",1} } },  -- item 2455
    ["Minor Rejuvenation Potion"] = { skill = 40, reagents = { {"Mageroyal",1}, {"Peacebloom",1}, {"Empty Vial",1} } },  -- item 2456
    ["Nature Protection Potion"] = { skill = 190, reagents = { {"Liferoot",1}, {"Stranglekelp",1}, {"Leaded Vial",1} } },  -- item 6052
    ["Oil of Immolation"] = { skill = 205, reagents = { {"Firebloom",1}, {"Goldthorn",1}, {"Crystal Vial",1} } },  -- item 8956
    ["Philosopher's Stone"] = { skill = 225, reagents = { {"Iron Bar",1}, {"Black Vitriol",1}, {"Purple Lotus",1}, {"Firebloom",1} } },  -- item 9149
    ["Purification Potion"] = { skill = 285, reagents = { {"Icecap",1}, {"Plaguebloom",1}, {"Crystal Vial",1} } },  -- item 13462
    ["Rage Potion"] = { skill = 60, reagents = { {"Sharp Claw",1}, {"Briarthorn",1}, {"Empty Vial",1} } },  -- item 5631
    ["Restorative Potion"] = { skill = 215, reagents = { {"Elemental Earth",1}, {"Goldthorn",1}, {"Crystal Vial",1} } },  -- item 9030
    ["Shadow Oil"] = { skill = 165, reagents = { {"Fadeleaf",1}, {"Grave Moss",1}, {"Leaded Vial",1} } },  -- item 3824
    ["Shadow Protection Potion"] = { skill = 135, reagents = { {"Grave Moss",1}, {"Kingsblood",1}, {"Leaded Vial",1} } },  -- item 6048
    ["Stonescale Oil"] = { skill = 250, reagents = { {"Stonescale Eel",1}, {"Leaded Vial",1} } },  -- item 13423
    ["Strong Troll's Blood Potion"] = { skill = 125, reagents = { {"Bruiseweed",1}, {"Briarthorn",1}, {"Leaded Vial",1} } },  -- item 3388
    ["Superior Healing Potion"] = { skill = 215, reagents = { {"Sungrass",1}, {"Khadgar's Whisker",1}, {"Crystal Vial",1} } },  -- item 3928
    ["Superior Mana Potion"] = { skill = 260, reagents = { {"Sungrass",2}, {"Blindweed",2}, {"Crystal Vial",1} } },  -- item 13443
    ["Swiftness Potion"] = { skill = 60, reagents = { {"Swiftthistle",1}, {"Briarthorn",1}, {"Empty Vial",1} } },  -- item 2459
    ["Swim Speed Potion"] = { skill = 100, reagents = { {"Swiftthistle",1}, {"Blackmouth Oil",1}, {"Empty Vial",1} } },  -- item 6372
    ["The Alchemist's Stone"] = { skill = 300, reagents = { {"Essence of Fire",1}, {"Essence of Earth",1}, {"Essence of Air",1}, {"Essence of Water",1}, {"Living Essence",1}, {"Black Vitriol",1}, {"Black Lotus",1} } },  -- item 13503
    ["Transmute: Air to Fire"] = { skill = 275, reagents = { {"Essence of Air",1} } },  -- item 7078
    ["Transmute: Arcanite"] = { skill = 275, reagents = { {"Thorium Bar",1}, {"Arcane Crystal",1} } },  -- item 12360
    ["Transmute: Earth to Life"] = { skill = 275, reagents = { {"Essence of Earth",1} } },  -- item 12803
    ["Transmute: Earth to Water"] = { skill = 275, reagents = { {"Essence of Earth",1} } },  -- item 7080
    ["Transmute: Fire to Earth"] = { skill = 275, reagents = { {"Essence of Fire",1} } },  -- item 7076
    ["Transmute: Iron to Gold"] = { skill = 225, reagents = { {"Iron Bar",1} } },  -- item 3577
    ["Transmute: Life to Earth"] = { skill = 275, reagents = { {"Living Essence",1} } },  -- item 7076
    ["Transmute: Mithril to Truesilver"] = { skill = 225, reagents = { {"Mithril Bar",1} } },  -- item 6037
    ["Transmute: Undeath to Water"] = { skill = 275, reagents = { {"Essence of Undeath",1} } },  -- item 7080
    ["Transmute: Water to Air"] = { skill = 275, reagents = { {"Essence of Water",1} } },  -- item 7082
    ["Transmute: Water to Undeath"] = { skill = 275, reagents = { {"Essence of Water",1} } },  -- item 12808
    ["Weak Troll's Blood Potion"] = { skill = 15, reagents = { {"Peacebloom",1}, {"Earthroot",1}, {"Empty Vial",1} } },  -- item 3382
    ["Wildvine Potion"] = { skill = 225, reagents = { {"Wildvine",1}, {"Purple Lotus",1}, {"Crystal Vial",1} } },  -- item 9144
}
