-- AUTO-GENERATED by tools/build_crafts.py. DO NOT EDIT BY HAND.
-- Crafted item name -> { prof, skill, reagents }. Tailoring/Engineering/etc. Used by
-- DropChanceTooltip material aggregation (crafted item -> "Crafted  <Profession> <skill>").
DropChanceTooltip_CraftRecipes = {
    ["Accurate Scope"] = { prof = "Engineering", skill = 180, reagents = { {"Bronze Tube",1}, {"Jade",1}, {"Citrine",1} } },  -- item 4407
    ["Admiral's Hat"] = { prof = "Tailoring", skill = 240, reagents = { {"Bolt of Mageweave",3}, {"Long Elegant Feather",6}, {"Heavy Silken Thread",2} } },  -- item 10030
    ["Advanced Target Dummy"] = { prof = "Engineering", skill = 185, reagents = { {"Iron Strut",1}, {"Bronze Framework",1}, {"Gyrochronatom",1}, {"Heavy Leather",4} } },  -- item 4392
    ["Alarm-O-Bot"] = { prof = "Engineering", skill = 265, reagents = { {"Thorium Bar",4}, {"Thorium Widget",2}, {"Rugged Leather",4}, {"Star Ruby",1}, {"Fused Wiring",1} } },  -- item 18645
    ["Aquadynamic Fish Attractor"] = { prof = "Engineering", skill = 150, reagents = { {"Bronze Bar",2}, {"Nightcrawlers",1}, {"Coarse Blasting Powder",1} } },  -- item 6533
    ["Arcane Bomb"] = { prof = "Engineering", skill = 300, reagents = { {"Delicate Arcanite Converter",1}, {"Thorium Bar",3}, {"Runecloth",1} } },  -- item 16040
    ["Arcanite Dragonling"] = { prof = "Engineering", skill = 300, reagents = { {"Mithril Mechanical Dragonling",1}, {"Delicate Arcanite Converter",8}, {"Enchanted Thorium Bar",10}, {"Thorium Widget",6}, {"Gold Power Core",4}, {"Enchanted Leather",6} } },  -- item 16022
    ["Arclight Spanner"] = { prof = "Engineering", skill = 50, reagents = { {"Copper Bar",6} } },  -- item 6219
    ["Argent Boots"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",6}, {"Enchanted Leather",4}, {"Golden Pearl",2}, {"Guardian Stone",2}, {"Ironweb Spider Silk",2} } },  -- item 19056
    ["Argent Shoulders"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",5}, {"Guardian Stone",2}, {"Ironweb Spider Silk",2} } },  -- item 19059
    ["Azure Shoulders"] = { prof = "Tailoring", skill = 190, reagents = { {"Bolt of Silk Cloth",6}, {"Naga Scale",2}, {"Blue Dye",2}, {"Silken Thread",2} } },  -- item 7060
    ["Azure Silk Belt"] = { prof = "Tailoring", skill = 175, reagents = { {"Bolt of Silk Cloth",4}, {"Elemental Water",1}, {"Blue Dye",2}, {"Fine Thread",2}, {"Iron Buckle",1} } },  -- item 7052
    ["Azure Silk Cloak"] = { prof = "Tailoring", skill = 175, reagents = { {"Bolt of Silk Cloth",3}, {"Blue Dye",2}, {"Fine Thread",2} } },  -- item 7053
    ["Azure Silk Gloves"] = { prof = "Tailoring", skill = 145, reagents = { {"Bolt of Silk Cloth",3}, {"Heavy Leather",2}, {"Blue Dye",2}, {"Fine Thread",2} } },  -- item 4319
    ["Azure Silk Hood"] = { prof = "Tailoring", skill = 145, reagents = { {"Bolt of Silk Cloth",2}, {"Blue Dye",2}, {"Fine Thread",1} } },  -- item 7048
    ["Azure Silk Pants"] = { prof = "Tailoring", skill = 140, reagents = { {"Bolt of Silk Cloth",4}, {"Blue Dye",2}, {"Fine Thread",3} } },  -- item 7046
    ["Azure Silk Vest"] = { prof = "Tailoring", skill = 150, reagents = { {"Bolt of Silk Cloth",5}, {"Blue Dye",4} } },  -- item 4324
    ["Barbaric Linen Vest"] = { prof = "Tailoring", skill = 70, reagents = { {"Bolt of Linen Cloth",4}, {"Light Leather",1}, {"Fine Thread",1} } },  -- item 2578
    ["Belt of the Archmage"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",16}, {"Ghost Dye",10}, {"Mooncloth",10}, {"Essence of Water",12}, {"Essence of Fire",12}, {"Large Brilliant Shard",6}, {"Rune Thread",6} } },  -- item 18405
    ["Big Bag of Enchantment"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",6}, {"Large Brilliant Shard",4}, {"Enchanted Leather",4}, {"Ironweb Spider Silk",4} } },  -- item 22249
    ["Big Bronze Bomb"] = { prof = "Engineering", skill = 140, reagents = { {"Heavy Blasting Powder",2}, {"Bronze Bar",3}, {"Silver Contact",1} } },  -- item 4380
    ["Big Iron Bomb"] = { prof = "Engineering", skill = 190, reagents = { {"Iron Bar",3}, {"Heavy Blasting Powder",3}, {"Silver Contact",1} } },  -- item 4394
    ["Biznicks 247x128 Accurascope"] = { prof = "Engineering", skill = 300, reagents = { {"Lava Core",2}, {"Essence of Earth",2}, {"Delicate Arcanite Converter",4}, {"Dark Iron Bar",6}, {"Thorium Tube",1} } },  -- item 18283
    ["Black Mageweave Boots"] = { prof = "Tailoring", skill = 230, reagents = { {"Bolt of Mageweave",3}, {"Heavy Silken Thread",2}, {"Thick Leather",2} } },  -- item 10026
    ["Black Mageweave Gloves"] = { prof = "Tailoring", skill = 215, reagents = { {"Bolt of Mageweave",2}, {"Heavy Silken Thread",2} } },  -- item 10003
    ["Black Mageweave Headband"] = { prof = "Tailoring", skill = 230, reagents = { {"Bolt of Mageweave",3}, {"Heavy Silken Thread",2} } },  -- item 10024
    ["Black Mageweave Leggings"] = { prof = "Tailoring", skill = 205, reagents = { {"Bolt of Mageweave",2}, {"Silken Thread",3} } },  -- item 9999
    ["Black Mageweave Robe"] = { prof = "Tailoring", skill = 210, reagents = { {"Bolt of Mageweave",3}, {"Heavy Silken Thread",1} } },  -- item 10001
    ["Black Mageweave Shoulders"] = { prof = "Tailoring", skill = 230, reagents = { {"Bolt of Mageweave",3}, {"Heavy Silken Thread",2} } },  -- item 10027
    ["Black Mageweave Vest"] = { prof = "Tailoring", skill = 205, reagents = { {"Bolt of Mageweave",2}, {"Silken Thread",3} } },  -- item 9998
    ["Black Silk Pack"] = { prof = "Tailoring", skill = 185, reagents = { {"Bolt of Silk Cloth",5}, {"Black Dye",1}, {"Fine Thread",4} } },  -- item 5765
    ["Black Swashbuckler's Shirt"] = { prof = "Tailoring", skill = 200, reagents = { {"Bolt of Silk Cloth",5}, {"Black Dye",1}, {"Silken Thread",1} } },  -- item 4336
    ["Bloodvine Boots"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",3}, {"Bloodvine",3}, {"Enchanted Leather",4}, {"Bolt of Runecloth",4}, {"Ironweb Spider Silk",4} } },  -- item 19684
    ["Bloodvine Goggles"] = { prof = "Engineering", skill = 300, reagents = { {"Bloodvine",4}, {"Souldarite",5}, {"Delicate Arcanite Converter",2}, {"Powerful Mojo",8}, {"Enchanted Leather",4} } },  -- item 19999
    ["Bloodvine Leggings"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",4}, {"Bloodvine",4}, {"Powerful Mojo",4}, {"Bolt of Runecloth",4}, {"Ironweb Spider Silk",2} } },  -- item 19683
    ["Bloodvine Lens"] = { prof = "Engineering", skill = 300, reagents = { {"Bloodvine",5}, {"Souldarite",5}, {"Delicate Arcanite Converter",1}, {"Powerful Mojo",8}, {"Enchanted Leather",4} } },  -- item 19998
    ["Bloodvine Vest"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",3}, {"Bloodvine",5}, {"Powerful Mojo",4}, {"Bolt of Runecloth",4}, {"Ironweb Spider Silk",2} } },  -- item 19682
    ["Blue Firework"] = { prof = "Engineering", skill = 150, reagents = { {"Heavy Blasting Powder",1}, {"Heavy Leather",1} } },  -- item 9312
    ["Blue Linen Robe"] = { prof = "Tailoring", skill = 70, reagents = { {"Bolt of Linen Cloth",4}, {"Coarse Thread",2}, {"Blue Dye",2} } },  -- item 6242
    ["Blue Linen Shirt"] = { prof = "Tailoring", skill = 40, reagents = { {"Bolt of Linen Cloth",2}, {"Coarse Thread",1}, {"Blue Dye",1} } },  -- item 2577
    ["Blue Linen Vest"] = { prof = "Tailoring", skill = 55, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",1}, {"Blue Dye",1} } },  -- item 6240
    ["Blue Overalls"] = { prof = "Tailoring", skill = 100, reagents = { {"Bolt of Woolen Cloth",4}, {"Fine Thread",2}, {"Blue Dye",2} } },  -- item 6263
    ["Blue Rocket Cluster"] = { prof = "Engineering", skill = 225, reagents = { {"Solid Blasting Powder",1}, {"Thick Leather",1} } },  -- item 21571
    ["Bolt of Linen Cloth"] = { prof = "Tailoring", skill = 1, reagents = { {"Linen Cloth",2} } },  -- item 2996
    ["Bolt of Mageweave"] = { prof = "Tailoring", skill = 175, reagents = { {"Mageweave Cloth",5} } },  -- item 4339
    ["Bolt of Runecloth"] = { prof = "Tailoring", skill = 250, reagents = { {"Runecloth",5} } },  -- item 14048
    ["Bolt of Silk Cloth"] = { prof = "Tailoring", skill = 125, reagents = { {"Silk Cloth",4} } },  -- item 4305
    ["Bolt of Woolen Cloth"] = { prof = "Tailoring", skill = 75, reagents = { {"Wool Cloth",3} } },  -- item 2997
    ["Boots of the Enchanter"] = { prof = "Tailoring", skill = 175, reagents = { {"Bolt of Silk Cloth",4}, {"Silken Thread",1}, {"Thick Spider's Silk",2} } },  -- item 4325
    ["Bottomless Bag"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",8}, {"Mooncloth",12}, {"Large Brilliant Shard",2}, {"Core Leather",2}, {"Rune Thread",2} } },  -- item 14156
    ["Bright Yellow Shirt"] = { prof = "Tailoring", skill = 135, reagents = { {"Bolt of Silk Cloth",1}, {"Yellow Dye",1}, {"Fine Thread",1} } },  -- item 4332
    ["Bright-Eye Goggles"] = { prof = "Engineering", skill = 175, reagents = { {"Heavy Leather",6}, {"Citrine",2} } },  -- item 10499
    ["Brightcloth Cloak"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",4}, {"Gold Bar",2}, {"Rune Thread",1} } },  -- item 14103
    ["Brightcloth Gloves"] = { prof = "Tailoring", skill = 270, reagents = { {"Bolt of Runecloth",4}, {"Gold Bar",2}, {"Rune Thread",1} } },  -- item 14101
    ["Brightcloth Pants"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",6}, {"Gold Bar",4}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 14104
    ["Brightcloth Robe"] = { prof = "Tailoring", skill = 270, reagents = { {"Bolt of Runecloth",5}, {"Gold Bar",2}, {"Rune Thread",1} } },  -- item 14100
    ["Bronze Framework"] = { prof = "Engineering", skill = 145, reagents = { {"Bronze Bar",2}, {"Medium Leather",1}, {"Wool Cloth",1} } },  -- item 4382
    ["Bronze Tube"] = { prof = "Engineering", skill = 105, reagents = { {"Bronze Bar",2}, {"Weak Flux",1} } },  -- item 4371
    ["Brown Linen Pants"] = { prof = "Tailoring", skill = 30, reagents = { {"Bolt of Linen Cloth",2}, {"Coarse Thread",1} } },  -- item 4343
    ["Brown Linen Robe"] = { prof = "Tailoring", skill = 30, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",1} } },  -- item 6238
    ["Brown Linen Shirt"] = { prof = "Tailoring", skill = 1, reagents = { {"Bolt of Linen Cloth",1}, {"Coarse Thread",1} } },  -- item 4344
    ["Brown Linen Vest"] = { prof = "Tailoring", skill = 10, reagents = { {"Bolt of Linen Cloth",1}, {"Coarse Thread",1} } },  -- item 2568
    ["Catseye Ultra Goggles"] = { prof = "Engineering", skill = 220, reagents = { {"Thick Leather",4}, {"Aquamarine",2}, {"Catseye Elixir",1} } },  -- item 10501
    ["Cenarion Herb Bag"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",5}, {"Purple Lotus",10}, {"Morrowgrain",8}, {"Rune Thread",2} } },  -- item 22251
    ["Cindercloth Boots"] = { prof = "Tailoring", skill = 245, reagents = { {"Bolt of Mageweave",5}, {"Heart of Fire",1}, {"Heavy Silken Thread",3}, {"Thick Leather",2} } },  -- item 10044
    ["Cindercloth Cloak"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",5}, {"Essence of Fire",1}, {"Rune Thread",1} } },  -- item 14044
    ["Cindercloth Gloves"] = { prof = "Tailoring", skill = 270, reagents = { {"Bolt of Runecloth",4}, {"Heart of Fire",3}, {"Rune Thread",1} } },  -- item 14043
    ["Cindercloth Pants"] = { prof = "Tailoring", skill = 280, reagents = { {"Bolt of Runecloth",6}, {"Essence of Fire",1}, {"Rune Thread",1} } },  -- item 14045
    ["Cindercloth Robe"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",5}, {"Heart of Fire",2}, {"Heavy Silken Thread",2} } },  -- item 10042
    ["Cindercloth Vest"] = { prof = "Tailoring", skill = 260, reagents = { {"Bolt of Runecloth",5}, {"Heart of Fire",3}, {"Rune Thread",1} } },  -- item 14042
    ["Cloak of Fire"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",6}, {"Essence of Fire",4}, {"Heart of Fire",4}, {"Elemental Fire",4}, {"Rune Thread",1} } },  -- item 14134
    ["Cloak of Warding"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Guardian Stone",4}, {"Arcanite Bar",1}, {"Rune Thread",2} } },  -- item 18413
    ["Coarse Blasting Powder"] = { prof = "Engineering", skill = 75, reagents = { {"Coarse Stone",1} } },  -- item 4364
    ["Coarse Dynamite"] = { prof = "Engineering", skill = 75, reagents = { {"Coarse Blasting Powder",3}, {"Linen Cloth",1} } },  -- item 4365
    ["Colorful Kilt"] = { prof = "Tailoring", skill = 120, reagents = { {"Bolt of Woolen Cloth",5}, {"Red Dye",3}, {"Fine Thread",1} } },  -- item 10048
    ["Compact Harvest Reaper Kit"] = { prof = "Engineering", skill = 175, reagents = { {"Iron Strut",2}, {"Bronze Framework",1}, {"Gyrochronatom",2}, {"Heavy Leather",4} } },  -- item 4391
    ["Copper Modulator"] = { prof = "Engineering", skill = 65, reagents = { {"Handful of Copper Bolts",2}, {"Copper Bar",1}, {"Linen Cloth",2} } },  -- item 4363
    ["Copper Tube"] = { prof = "Engineering", skill = 50, reagents = { {"Copper Bar",2}, {"Weak Flux",1} } },  -- item 4361
    ["Core Felcloth Bag"] = { prof = "Tailoring", skill = 300, reagents = { {"Felcloth",20}, {"Core Leather",16}, {"Bloodvine",8}, {"Essence of Fire",4}, {"Ironweb Spider Silk",4} } },  -- item 21342
    ["Core Marksman Rifle"] = { prof = "Engineering", skill = 300, reagents = { {"Fiery Core",4}, {"Lava Core",2}, {"Arcanite Bar",6}, {"Delicate Arcanite Converter",2}, {"Thorium Tube",2} } },  -- item 18282
    ["Crafted Heavy Shot"] = { prof = "Engineering", skill = 75, reagents = { {"Coarse Blasting Powder",1}, {"Copper Bar",1} } },  -- item 8068
    ["Crafted Light Shot"] = { prof = "Engineering", skill = 30, reagents = { {"Rough Blasting Powder",1}, {"Copper Bar",1} } },  -- item 8067
    ["Crafted Solid Shot"] = { prof = "Engineering", skill = 125, reagents = { {"Heavy Blasting Powder",1}, {"Bronze Bar",1} } },  -- item 8069
    ["Craftsman's Monocle"] = { prof = "Engineering", skill = 185, reagents = { {"Heavy Leather",6}, {"Citrine",2} } },  -- item 4393
    ["Crimson Silk Belt"] = { prof = "Tailoring", skill = 175, reagents = { {"Bolt of Silk Cloth",4}, {"Iron Buckle",1}, {"Red Dye",2}, {"Silken Thread",1} } },  -- item 7055
    ["Crimson Silk Cloak"] = { prof = "Tailoring", skill = 180, reagents = { {"Bolt of Silk Cloth",5}, {"Red Dye",2}, {"Fire Oil",2}, {"Silken Thread",1} } },  -- item 7056
    ["Crimson Silk Gloves"] = { prof = "Tailoring", skill = 210, reagents = { {"Bolt of Silk Cloth",6}, {"Elemental Fire",2}, {"Fire Oil",2}, {"Thick Leather",2}, {"Red Dye",4}, {"Silken Thread",2} } },  -- item 7064
    ["Crimson Silk Pantaloons"] = { prof = "Tailoring", skill = 195, reagents = { {"Bolt of Silk Cloth",4}, {"Red Dye",2}, {"Silken Thread",2} } },  -- item 7062
    ["Crimson Silk Robe"] = { prof = "Tailoring", skill = 205, reagents = { {"Bolt of Silk Cloth",8}, {"Elemental Fire",4}, {"Mana Potion",2}, {"Red Dye",4}, {"Silken Thread",1} } },  -- item 7063
    ["Crimson Silk Shoulders"] = { prof = "Tailoring", skill = 190, reagents = { {"Bolt of Silk Cloth",5}, {"Fire Oil",2}, {"Red Dye",2}, {"Silken Thread",2} } },  -- item 7059
    ["Crimson Silk Vest"] = { prof = "Tailoring", skill = 185, reagents = { {"Bolt of Silk Cloth",4}, {"Red Dye",2}, {"Fine Thread",2} } },  -- item 7058
    ["Crude Scope"] = { prof = "Engineering", skill = 60, reagents = { {"Copper Tube",1}, {"Malachite",1}, {"Handful of Copper Bolts",1} } },  -- item 4405
    ["Dark Iron Bomb"] = { prof = "Engineering", skill = 285, reagents = { {"Thorium Widget",2}, {"Dark Iron Bar",1}, {"Dense Blasting Powder",3}, {"Runecloth",3} } },  -- item 16005
    ["Dark Iron Rifle"] = { prof = "Engineering", skill = 275, reagents = { {"Thorium Tube",2}, {"Dark Iron Bar",6}, {"Deadly Scope",2}, {"Blue Sapphire",2}, {"Large Opal",2}, {"Rugged Leather",4} } },  -- item 16004
    ["Dark Silk Shirt"] = { prof = "Tailoring", skill = 155, reagents = { {"Bolt of Silk Cloth",2}, {"Gray Dye",2}, {"Fine Thread",1} } },  -- item 4333
    ["Deadly Blunderbuss"] = { prof = "Engineering", skill = 105, reagents = { {"Copper Tube",2}, {"Handful of Copper Bolts",4}, {"Wooden Stock",1}, {"Medium Leather",2} } },  -- item 4369
    ["Deadly Scope"] = { prof = "Engineering", skill = 210, reagents = { {"Mithril Tube",1}, {"Aquamarine",2}, {"Thick Leather",2} } },  -- item 10546
    ["Deepdive Helmet"] = { prof = "Engineering", skill = 230, reagents = { {"Mithril Bar",8}, {"Mithril Casing",1}, {"Truesilver Bar",1}, {"Tigerseye",4}, {"Malachite",4} } },  -- item 10506
    ["Delicate Arcanite Converter"] = { prof = "Engineering", skill = 285, reagents = { {"Arcanite Bar",1}, {"Ironweb Spider Silk",1} } },  -- item 16006
    ["Dense Blasting Powder"] = { prof = "Engineering", skill = 250, reagents = { {"Dense Stone",2} } },  -- item 15992
    ["Dense Dynamite"] = { prof = "Engineering", skill = 250, reagents = { {"Dense Blasting Powder",2}, {"Runecloth",3} } },  -- item 18641
    ["Dimensional Ripper - Everlook"] = { prof = "Engineering", skill = 285, reagents = { {"Mithril Bar",10}, {"Truesilver Transformer",1}, {"Heart of Fire",4}, {"Star Ruby",2}, {"The Big One",1} } },  -- item 18984
    ["Discombobulator Ray"] = { prof = "Engineering", skill = 160, reagents = { {"Whirring Bronze Gizmo",3}, {"Silk Cloth",2}, {"Jade",1}, {"Bronze Tube",1} } },  -- item 4388
    ["Double-stitched Woolen Shoulders"] = { prof = "Tailoring", skill = 110, reagents = { {"Bolt of Woolen Cloth",3}, {"Fine Thread",2} } },  -- item 4314
    ["Dreamweave Circlet"] = { prof = "Tailoring", skill = 250, reagents = { {"Bolt of Mageweave",8}, {"Wildvine",4}, {"Heart of the Wild",2}, {"Heavy Silken Thread",3}, {"Truesilver Bar",1}, {"Jade",1} } },  -- item 10041
    ["Dreamweave Gloves"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",4}, {"Wildvine",4}, {"Heart of the Wild",2}, {"Heavy Silken Thread",2} } },  -- item 10019
    ["Dreamweave Vest"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",6}, {"Wildvine",6}, {"Heart of the Wild",2}, {"Heavy Silken Thread",2} } },  -- item 10021
    ["Earthen Silk Belt"] = { prof = "Tailoring", skill = 195, reagents = { {"Bolt of Silk Cloth",5}, {"Elemental Earth",4}, {"Heavy Leather",4}, {"Iron Buckle",1}, {"Silken Thread",2} } },  -- item 7061
    ["Earthen Vest"] = { prof = "Tailoring", skill = 170, reagents = { {"Bolt of Silk Cloth",3}, {"Elemental Earth",1}, {"Fine Thread",2} } },  -- item 7051
    ["Enchanted Mageweave Pouch"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",4}, {"Vision Dust",4}, {"Heavy Silken Thread",2} } },  -- item 22246
    ["Enchanted Runecloth Bag"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",5}, {"Greater Eternal Essence",2}, {"Rune Thread",2} } },  -- item 22248
    ["Enchanter's Cowl"] = { prof = "Tailoring", skill = 165, reagents = { {"Bolt of Silk Cloth",3}, {"Fine Thread",2}, {"Thick Spider's Silk",2} } },  -- item 4322
    ["Explosive Sheep"] = { prof = "Engineering", skill = 150, reagents = { {"Bronze Framework",1}, {"Whirring Bronze Gizmo",1}, {"Heavy Blasting Powder",2}, {"Wool Cloth",2} } },  -- item 4384
    ["EZ-Thro Dynamite"] = { prof = "Engineering", skill = 100, reagents = { {"Coarse Blasting Powder",4}, {"Wool Cloth",1} } },  -- item 6714
    ["EZ-Thro Dynamite II"] = { prof = "Engineering", skill = 200, reagents = { {"Solid Blasting Powder",1}, {"Mageweave Cloth",2} } },  -- item 18588
    ["Felcloth Bag"] = { prof = "Tailoring", skill = 285, reagents = { {"Felcloth",12}, {"Enchanted Leather",6}, {"Dark Rune",2}, {"Ironweb Spider Silk",4} } },  -- item 21341
    ["Felcloth Boots"] = { prof = "Tailoring", skill = 285, reagents = { {"Bolt of Runecloth",6}, {"Felcloth",4}, {"Rugged Leather",4}, {"Rune Thread",1} } },  -- item 14108
    ["Felcloth Gloves"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Felcloth",20}, {"Demonic Rune",6}, {"Essence of Undeath",8}, {"Rune Thread",2} } },  -- item 18407
    ["Felcloth Hood"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",5}, {"Felcloth",4}, {"Rune Thread",1} } },  -- item 14111
    ["Felcloth Pants"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",5}, {"Felcloth",4}, {"Rune Thread",1} } },  -- item 14107
    ["Felcloth Robe"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",8}, {"Felcloth",8}, {"Demonic Rune",4}, {"Rune Thread",2} } },  -- item 14106
    ["Felcloth Shoulders"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",7}, {"Felcloth",6}, {"Demonic Rune",4}, {"Rugged Leather",4}, {"Rune Thread",2} } },  -- item 14112
    ["Festive Red Dress"] = { prof = "Tailoring", skill = 250, reagents = { {"Bolt of Runecloth",4}, {"Firebloom",2}, {"Red Dye",2}, {"Rune Thread",1} } },  -- item 21154
    ["Festive Red Pant Suit"] = { prof = "Tailoring", skill = 250, reagents = { {"Bolt of Runecloth",4}, {"Firebloom",2}, {"Red Dye",2}, {"Rune Thread",1} } },  -- item 21542
    ["Field Repair Bot 74A"] = { prof = "Engineering", skill = 300, reagents = { {"Thorium Bar",12}, {"Rugged Leather",4}, {"Fused Wiring",1}, {"Elemental Earth",2}, {"Elemental Fire",1} } },  -- item 18232
    ["Fire Goggles"] = { prof = "Engineering", skill = 205, reagents = { {"Green Tinted Goggles",1}, {"Citrine",2}, {"Elemental Fire",2}, {"Heavy Leather",4} } },  -- item 10500
    ["Firework Cluster Launcher"] = { prof = "Engineering", skill = 275, reagents = { {"Inlaid Mithril Cylinder",4}, {"Goblin Rocket Fuel",4}, {"Truesilver Transformer",2}, {"Mithril Casing",1} } },  -- item 21570
    ["Firework Launcher"] = { prof = "Engineering", skill = 225, reagents = { {"Inlaid Mithril Cylinder",1}, {"Goblin Rocket Fuel",1}, {"Unstable Trigger",1}, {"Mithril Casing",1} } },  -- item 21569
    ["Flame Deflector"] = { prof = "Engineering", skill = 125, reagents = { {"Whirring Bronze Gizmo",1}, {"Small Flame Sac",1} } },  -- item 4376
    ["Flarecore Gloves"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",8}, {"Fiery Core",6}, {"Essence of Fire",4}, {"Enchanted Leather",2}, {"Rune Thread",2} } },  -- item 16979
    ["Flarecore Leggings"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",8}, {"Fiery Core",5}, {"Lava Core",3}, {"Essence of Fire",10}, {"Ironweb Spider Silk",4} } },  -- item 19165
    ["Flarecore Mantle"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Fiery Core",4}, {"Lava Core",4}, {"Enchanted Leather",6}, {"Rune Thread",2} } },  -- item 16980
    ["Flarecore Robe"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",10}, {"Fiery Core",2}, {"Lava Core",3}, {"Essence of Fire",6}, {"Ironweb Spider Silk",4} } },  -- item 19156
    ["Flarecore Wraps"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",6}, {"Fiery Core",8}, {"Essence of Fire",2}, {"Enchanted Leather",6}, {"Rune Thread",4} } },  -- item 18263
    ["Flash Bomb"] = { prof = "Engineering", skill = 185, reagents = { {"Blue Pearl",1}, {"Heavy Blasting Powder",1}, {"Silk Cloth",1} } },  -- item 4852
    ["Flawless Arcanite Rifle"] = { prof = "Engineering", skill = 300, reagents = { {"Arcanite Bar",10}, {"Thorium Tube",2}, {"Essence of Fire",2}, {"Essence of Earth",2}, {"Azerothian Diamond",2}, {"Enchanted Leather",2} } },  -- item 16007
    ["Flying Tiger Goggles"] = { prof = "Engineering", skill = 100, reagents = { {"Light Leather",6}, {"Tigerseye",2} } },  -- item 4368
    ["Force Reactive Disk"] = { prof = "Engineering", skill = 300, reagents = { {"Arcanite Bar",6}, {"Delicate Arcanite Converter",2}, {"Essence of Air",8}, {"Living Essence",12}, {"Essence of Earth",8} } },  -- item 18168
    ["Formal White Shirt"] = { prof = "Tailoring", skill = 170, reagents = { {"Bolt of Silk Cloth",3}, {"Bleach",2}, {"Fine Thread",1} } },  -- item 4334
    ["Frostweave Gloves"] = { prof = "Tailoring", skill = 265, reagents = { {"Bolt of Runecloth",3}, {"Essence of Water",1}, {"Rune Thread",1} } },  -- item 13870
    ["Frostweave Pants"] = { prof = "Tailoring", skill = 280, reagents = { {"Bolt of Runecloth",6}, {"Essence of Water",1}, {"Rune Thread",1} } },  -- item 13871
    ["Frostweave Robe"] = { prof = "Tailoring", skill = 255, reagents = { {"Bolt of Runecloth",5}, {"Globe of Water",2}, {"Rune Thread",1} } },  -- item 13868
    ["Frostweave Tunic"] = { prof = "Tailoring", skill = 255, reagents = { {"Bolt of Runecloth",5}, {"Globe of Water",2}, {"Rune Thread",1} } },  -- item 13869
    ["Gaea's Embrace"] = { prof = "Tailoring", skill = 300, reagents = { {"Bloodvine",1}, {"Mooncloth",2}, {"Living Essence",4}, {"Ironweb Spider Silk",4} } },  -- item 22660
    ["Ghostweave Belt"] = { prof = "Tailoring", skill = 265, reagents = { {"Bolt of Runecloth",3}, {"Ghost Dye",2}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 14143
    ["Ghostweave Gloves"] = { prof = "Tailoring", skill = 270, reagents = { {"Bolt of Runecloth",4}, {"Ghost Dye",2}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 14142
    ["Ghostweave Pants"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",6}, {"Ghost Dye",4}, {"Rune Thread",1} } },  -- item 14144
    ["Ghostweave Vest"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",6}, {"Ghost Dye",4}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 14141
    ["Glacial Cloak"] = { prof = "Tailoring", skill = 300, reagents = { {"Frozen Rune",5}, {"Bolt of Runecloth",4}, {"Essence of Water",2}, {"Ironweb Spider Silk",4} } },  -- item 22658
    ["Glacial Gloves"] = { prof = "Tailoring", skill = 300, reagents = { {"Frozen Rune",5}, {"Bolt of Runecloth",4}, {"Essence of Water",4}, {"Ironweb Spider Silk",4} } },  -- item 22654
    ["Glacial Vest"] = { prof = "Tailoring", skill = 300, reagents = { {"Frozen Rune",7}, {"Bolt of Runecloth",8}, {"Essence of Water",6}, {"Ironweb Spider Silk",8} } },  -- item 22652
    ["Glacial Wrists"] = { prof = "Tailoring", skill = 300, reagents = { {"Frozen Rune",4}, {"Bolt of Runecloth",2}, {"Essence of Water",2}, {"Ironweb Spider Silk",4} } },  -- item 22655
    ["Gloves of Meditation"] = { prof = "Tailoring", skill = 130, reagents = { {"Bolt of Woolen Cloth",4}, {"Fine Thread",3}, {"Elixir of Wisdom",1} } },  -- item 4318
    ["Gloves of Spell Mastery"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",10}, {"Mooncloth",10}, {"Ghost Dye",10}, {"Golden Pearl",6}, {"Huge Emerald",6}, {"Enchanted Leather",8}, {"Rune Thread",2} } },  -- item 14146
    ["Gnomish Battle Chicken"] = { prof = "Engineering", skill = 230, reagents = { {"Mithril Casing",1}, {"Truesilver Bar",6}, {"Mithril Bar",6}, {"Inlaid Mithril Cylinder",2}, {"Gold Power Core",1}, {"Jade",2} } },  -- item 10725
    ["Gnomish Cloaking Device"] = { prof = "Engineering", skill = 200, reagents = { {"Gyrochronatom",4}, {"Jade",2}, {"Lesser Moonstone",2}, {"Citrine",2}, {"Fused Wiring",1} } },  -- item 4397
    ["Gnomish Death Ray"] = { prof = "Engineering", skill = 240, reagents = { {"Mithril Tube",2}, {"Unstable Trigger",1}, {"Essence of Undeath",1}, {"Ichor of Undeath",4}, {"Inlaid Mithril Cylinder",1} } },  -- item 10645
    ["Gnomish Goggles"] = { prof = "Engineering", skill = 210, reagents = { {"Fire Goggles",1}, {"Mithril Tube",1}, {"Gold Power Core",2}, {"Flask of Mojo",2}, {"Heavy Leather",2} } },  -- item 10545
    ["Gnomish Harm Prevention Belt"] = { prof = "Engineering", skill = 215, reagents = { {"Dusky Belt",1}, {"Mithril Bar",4}, {"Truesilver Bar",2}, {"Unstable Trigger",1}, {"Aquamarine",2} } },  -- item 10721
    ["Gnomish Mind Control Cap"] = { prof = "Engineering", skill = 235, reagents = { {"Mithril Bar",10}, {"Truesilver Bar",4}, {"Gold Power Core",1}, {"Star Ruby",2}, {"Mageweave Cloth",4} } },  -- item 10726
    ["Gnomish Net-o-Matic Projector"] = { prof = "Engineering", skill = 210, reagents = { {"Mithril Tube",1}, {"Shadow Silk",2}, {"Thick Spider's Silk",4}, {"Solid Blasting Powder",2}, {"Mithril Bar",4} } },  -- item 10720
    ["Gnomish Rocket Boots"] = { prof = "Engineering", skill = 225, reagents = { {"Black Mageweave Boots",1}, {"Mithril Tube",2}, {"Heavy Leather",4}, {"Solid Blasting Powder",8}, {"Gyrochronatom",4} } },  -- item 10724
    ["Gnomish Shrink Ray"] = { prof = "Engineering", skill = 205, reagents = { {"Mithril Tube",1}, {"Unstable Trigger",1}, {"Mithril Bar",4}, {"Flask of Mojo",4}, {"Jade",2} } },  -- item 10716
    ["Gnomish Universal Remote"] = { prof = "Engineering", skill = 125, reagents = { {"Bronze Bar",6}, {"Whirring Bronze Gizmo",1}, {"Flask of Oil",2}, {"Tigerseye",1}, {"Malachite",1} } },  -- item 7506
    ["Goblin Bomb Dispenser"] = { prof = "Engineering", skill = 230, reagents = { {"Mithril Casing",2}, {"Solid Blasting Powder",4}, {"Truesilver Bar",6}, {"Unstable Trigger",1}, {"Accurate Scope",2} } },  -- item 10587
    ["Goblin Construction Helmet"] = { prof = "Engineering", skill = 205, reagents = { {"Mithril Bar",8}, {"Citrine",1}, {"Elemental Fire",4} } },  -- item 10543
    ["Goblin Dragon Gun"] = { prof = "Engineering", skill = 240, reagents = { {"Mithril Tube",2}, {"Goblin Rocket Fuel",4}, {"Mithril Bar",6}, {"Truesilver Bar",6}, {"Unstable Trigger",1} } },  -- item 10727
    ["Goblin Jumper Cables"] = { prof = "Engineering", skill = 165, reagents = { {"Iron Bar",6}, {"Whirring Bronze Gizmo",2}, {"Flask of Oil",2}, {"Silk Cloth",2}, {"Shadowgem",2}, {"Fused Wiring",1} } },  -- item 7148
    ["Goblin Jumper Cables XL"] = { prof = "Engineering", skill = 265, reagents = { {"Thorium Widget",2}, {"Truesilver Transformer",2}, {"Fused Wiring",2}, {"Ironweb Spider Silk",2}, {"Star Ruby",2} } },  -- item 18587
    ["Goblin Land Mine"] = { prof = "Engineering", skill = 195, reagents = { {"Heavy Blasting Powder",3}, {"Iron Bar",2}, {"Gyrochronatom",1} } },  -- item 4395
    ["Goblin Mining Helmet"] = { prof = "Engineering", skill = 205, reagents = { {"Mithril Bar",8}, {"Citrine",1}, {"Elemental Earth",4} } },  -- item 10542
    ["Goblin Mortar"] = { prof = "Engineering", skill = 225, reagents = { {"Mithril Tube",2}, {"Mithril Bar",4}, {"Solid Blasting Powder",5}, {"Gold Power Core",1}, {"Elemental Fire",1} } },  -- item 10577
    ["Goblin Rocket Boots"] = { prof = "Engineering", skill = 225, reagents = { {"Black Mageweave Boots",1}, {"Mithril Tube",2}, {"Heavy Leather",4}, {"Goblin Rocket Fuel",2}, {"Unstable Trigger",1} } },  -- item 7189
    ["Goblin Rocket Fuel"] = { prof = "Engineering", skill = 210, reagents = { {"Firebloom",1}, {"Volatile Rum",1}, {"Leaded Vial",1} } },  -- item 9061
    ["Goblin Rocket Helmet"] = { prof = "Engineering", skill = 245, reagents = { {"Goblin Construction Helmet",1}, {"Goblin Rocket Fuel",4}, {"Mithril Bar",4}, {"Unstable Trigger",1} } },  -- item 10588
    ["Goblin Sapper Charge"] = { prof = "Engineering", skill = 205, reagents = { {"Mageweave Cloth",1}, {"Solid Blasting Powder",3}, {"Unstable Trigger",1} } },  -- item 10646
    ["Gold Power Core"] = { prof = "Engineering", skill = 150, reagents = { {"Gold Bar",1} } },  -- item 10558
    ["Gordok Ogre Suit"] = { prof = "Tailoring", skill = 285, reagents = { {"Bolt of Runecloth",2}, {"Rugged Leather",4}, {"Ogre Tannin",1}, {"Rune Thread",1} } },  -- item 18258
    ["Gray Woolen Robe"] = { prof = "Tailoring", skill = 105, reagents = { {"Bolt of Woolen Cloth",4}, {"Fine Thread",3}, {"Gray Dye",1} } },  -- item 2585
    ["Gray Woolen Shirt"] = { prof = "Tailoring", skill = 100, reagents = { {"Bolt of Woolen Cloth",2}, {"Fine Thread",1}, {"Gray Dye",1} } },  -- item 2587
    ["Greater Adept's Robe"] = { prof = "Tailoring", skill = 115, reagents = { {"Bolt of Woolen Cloth",5}, {"Fine Thread",3}, {"Red Dye",3} } },  -- item 6264
    ["Green Firework"] = { prof = "Engineering", skill = 150, reagents = { {"Heavy Blasting Powder",1}, {"Heavy Leather",1} } },  -- item 9313
    ["Green Holiday Shirt"] = { prof = "Tailoring", skill = 190, reagents = { {"Bolt of Silk Cloth",5}, {"Green Dye",4}, {"Silken Thread",1} } },  -- item 17723
    ["Green Lens"] = { prof = "Engineering", skill = 245, reagents = { {"Thick Leather",8}, {"Jade",3}, {"Aquamarine",3}, {"Heart of the Wild",2}, {"Wildvine",2} } },  -- item 10504
    ["Green Linen Bracers"] = { prof = "Tailoring", skill = 60, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",2}, {"Green Dye",1} } },  -- item 4308
    ["Green Linen Shirt"] = { prof = "Tailoring", skill = 70, reagents = { {"Bolt of Linen Cloth",3}, {"Fine Thread",1}, {"Green Dye",1} } },  -- item 2579
    ["Green Rocket Cluster"] = { prof = "Engineering", skill = 225, reagents = { {"Solid Blasting Powder",1}, {"Thick Leather",1} } },  -- item 21574
    ["Green Silk Armor"] = { prof = "Tailoring", skill = 165, reagents = { {"Bolt of Silk Cloth",5}, {"Green Dye",2}, {"Silken Thread",1} } },  -- item 7065
    ["Green Silk Pack"] = { prof = "Tailoring", skill = 175, reagents = { {"Bolt of Silk Cloth",4}, {"Heavy Leather",3}, {"Fine Thread",3}, {"Green Dye",1} } },  -- item 5764
    ["Green Silken Shoulders"] = { prof = "Tailoring", skill = 180, reagents = { {"Bolt of Silk Cloth",5}, {"Silken Thread",2} } },  -- item 7057
    ["Green Tinted Goggles"] = { prof = "Engineering", skill = 150, reagents = { {"Medium Leather",4}, {"Moss Agate",2}, {"Flying Tiger Goggles",1} } },  -- item 4385
    ["Green Woolen Bag"] = { prof = "Tailoring", skill = 95, reagents = { {"Bolt of Woolen Cloth",4}, {"Green Dye",1}, {"Fine Thread",1} } },  -- item 4241
    ["Green Woolen Vest"] = { prof = "Tailoring", skill = 85, reagents = { {"Bolt of Woolen Cloth",2}, {"Fine Thread",2}, {"Green Dye",1} } },  -- item 2582
    ["Gyrochronatom"] = { prof = "Engineering", skill = 170, reagents = { {"Iron Bar",1}, {"Gold Power Core",1} } },  -- item 4389
    ["Gyrofreeze Ice Reflector"] = { prof = "Engineering", skill = 260, reagents = { {"Thorium Widget",6}, {"Truesilver Transformer",2}, {"Blue Sapphire",2}, {"Essence of Fire",4}, {"Frost Oil",2}, {"Icecap",4} } },  -- item 18634
    ["Gyromatic Micro-Adjustor"] = { prof = "Engineering", skill = 175, reagents = { {"Steel Bar",4} } },  -- item 10498
    ["Handful of Copper Bolts"] = { prof = "Engineering", skill = 30, reagents = { {"Copper Bar",1} } },  -- item 4359
    ["Hands of Darkness"] = { prof = "Tailoring", skill = 145, reagents = { {"Bolt of Silk Cloth",3}, {"Heavy Leather",2}, {"Shadow Protection Potion",2}, {"Fine Thread",2} } },  -- item 7047
    ["Handstitched Linen Britches"] = { prof = "Tailoring", skill = 70, reagents = { {"Bolt of Linen Cloth",4}, {"Fine Thread",2} } },  -- item 4309
    ["Heavy Blasting Powder"] = { prof = "Engineering", skill = 125, reagents = { {"Heavy Stone",1} } },  -- item 4377
    ["Heavy Dynamite"] = { prof = "Engineering", skill = 125, reagents = { {"Heavy Blasting Powder",2}, {"Wool Cloth",1} } },  -- item 4378
    ["Heavy Linen Gloves"] = { prof = "Tailoring", skill = 35, reagents = { {"Bolt of Linen Cloth",2}, {"Coarse Thread",1} } },  -- item 4307
    ["Heavy Woolen Cloak"] = { prof = "Tailoring", skill = 100, reagents = { {"Bolt of Woolen Cloth",3}, {"Fine Thread",2}, {"Small Lustrous Pearl",2} } },  -- item 4311
    ["Heavy Woolen Gloves"] = { prof = "Tailoring", skill = 85, reagents = { {"Bolt of Woolen Cloth",3}, {"Fine Thread",1} } },  -- item 4310
    ["Heavy Woolen Pants"] = { prof = "Tailoring", skill = 110, reagents = { {"Bolt of Woolen Cloth",5}, {"Fine Thread",4} } },  -- item 4316
    ["Hi-Explosive Bomb"] = { prof = "Engineering", skill = 235, reagents = { {"Mithril Casing",2}, {"Unstable Trigger",1}, {"Solid Blasting Powder",2} } },  -- item 10562
    ["Hi-Impact Mithril Slugs"] = { prof = "Engineering", skill = 210, reagents = { {"Mithril Bar",1}, {"Solid Blasting Powder",1} } },  -- item 10512
    ["Hyper-Radiant Flame Reflector"] = { prof = "Engineering", skill = 290, reagents = { {"Dark Iron Bar",4}, {"Truesilver Transformer",3}, {"Essence of Water",6}, {"Star Ruby",4}, {"Azerothian Diamond",2} } },  -- item 18638
    ["Ice Deflector"] = { prof = "Engineering", skill = 155, reagents = { {"Whirring Bronze Gizmo",1}, {"Frost Oil",1} } },  -- item 4386
    ["Icy Cloak"] = { prof = "Tailoring", skill = 200, reagents = { {"Bolt of Mageweave",3}, {"Silken Thread",2}, {"Frost Oil",1}, {"Thick Spider's Silk",2} } },  -- item 4327
    ["Inferno Gloves"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Essence of Fire",10}, {"Star Ruby",2}, {"Rune Thread",2} } },  -- item 18408
    ["Inlaid Mithril Cylinder"] = { prof = "Engineering", skill = 200, reagents = { {"Mithril Bar",5}, {"Gold Bar",1}, {"Truesilver Bar",1} } },  -- item 9060
    ["Iron Grenade"] = { prof = "Engineering", skill = 175, reagents = { {"Iron Bar",1}, {"Heavy Blasting Powder",1}, {"Silk Cloth",1} } },  -- item 4390
    ["Iron Strut"] = { prof = "Engineering", skill = 160, reagents = { {"Iron Bar",2} } },  -- item 4387
    ["Large Blue Rocket"] = { prof = "Engineering", skill = 175, reagents = { {"Heavy Blasting Powder",1}, {"Heavy Leather",1} } },  -- item 21589
    ["Large Blue Rocket Cluster"] = { prof = "Engineering", skill = 275, reagents = { {"Dense Blasting Powder",1}, {"Rugged Leather",1} } },  -- item 21714
    ["Large Copper Bomb"] = { prof = "Engineering", skill = 105, reagents = { {"Copper Bar",3}, {"Coarse Blasting Powder",4}, {"Silver Contact",1} } },  -- item 4370
    ["Large Green Rocket"] = { prof = "Engineering", skill = 175, reagents = { {"Heavy Blasting Powder",1}, {"Heavy Leather",1} } },  -- item 21590
    ["Large Green Rocket Cluster"] = { prof = "Engineering", skill = 275, reagents = { {"Dense Blasting Powder",1}, {"Rugged Leather",1} } },  -- item 21716
    ["Large Red Rocket"] = { prof = "Engineering", skill = 175, reagents = { {"Heavy Blasting Powder",1}, {"Heavy Leather",1} } },  -- item 21592
    ["Large Red Rocket Cluster"] = { prof = "Engineering", skill = 275, reagents = { {"Dense Blasting Powder",1}, {"Rugged Leather",1} } },  -- item 21718
    ["Large Seaforium Charge"] = { prof = "Engineering", skill = 200, reagents = { {"Solid Blasting Powder",2}, {"Heavy Leather",2}, {"Refreshing Spring Water",1} } },  -- item 4398
    ["Lavender Mageweave Shirt"] = { prof = "Tailoring", skill = 230, reagents = { {"Bolt of Mageweave",2}, {"Purple Dye",2}, {"Heavy Silken Thread",2} } },  -- item 10054
    ["Lesser Wizard's Robe"] = { prof = "Tailoring", skill = 135, reagents = { {"Bolt of Silk Cloth",2}, {"Fine Thread",2}, {"Spider's Silk",2} } },  -- item 5766
    ["Lifelike Mechanical Toad"] = { prof = "Engineering", skill = 265, reagents = { {"Living Essence",1}, {"Thorium Widget",4}, {"Gold Power Core",1}, {"Rugged Leather",1} } },  -- item 15996
    ["Lil' Smoky"] = { prof = "Engineering", skill = 205, reagents = { {"Core of Earth",1}, {"Gyrochronatom",2}, {"Fused Wiring",1}, {"Mithril Bar",2}, {"Truesilver Bar",1} } },  -- item 11826
    ["Linen Bag"] = { prof = "Tailoring", skill = 45, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",3} } },  -- item 4238
    ["Linen Belt"] = { prof = "Tailoring", skill = 15, reagents = { {"Bolt of Linen Cloth",1}, {"Coarse Thread",1} } },  -- item 7026
    ["Linen Boots"] = { prof = "Tailoring", skill = 65, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",1}, {"Light Leather",1} } },  -- item 2569
    ["Linen Cloak"] = { prof = "Tailoring", skill = 1, reagents = { {"Bolt of Linen Cloth",1}, {"Coarse Thread",1} } },  -- item 2570
    ["Long Silken Cloak"] = { prof = "Tailoring", skill = 185, reagents = { {"Bolt of Silk Cloth",4}, {"Mana Potion",1}, {"Silken Thread",1} } },  -- item 4326
    ["Lovingly Crafted Boomstick"] = { prof = "Engineering", skill = 120, reagents = { {"Bronze Tube",2}, {"Handful of Copper Bolts",2}, {"Heavy Stock",1}, {"Moss Agate",3} } },  -- item 4372
    ["Mageweave Bag"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",4}, {"Silken Thread",2} } },  -- item 10050
    ["Major Recombobulator"] = { prof = "Engineering", skill = 275, reagents = { {"Thorium Tube",2}, {"Truesilver Transformer",1}, {"Runecloth",2} } },  -- item 18637
    ["Mantle of the Timbermaw"] = { prof = "Tailoring", skill = 300, reagents = { {"Mooncloth",5}, {"Essence of Earth",5}, {"Living Essence",5}, {"Ironweb Spider Silk",2} } },  -- item 19050
    ["Master Engineer's Goggles"] = { prof = "Engineering", skill = 290, reagents = { {"Fire Goggles",1}, {"Huge Emerald",2}, {"Enchanted Leather",4} } },  -- item 16008
    ["Masterwork Target Dummy"] = { prof = "Engineering", skill = 275, reagents = { {"Mithril Casing",1}, {"Thorium Tube",1}, {"Thorium Widget",2}, {"Truesilver Bar",1}, {"Rugged Leather",2}, {"Runecloth",4} } },  -- item 16023
    ["Mechanical Dragonling"] = { prof = "Engineering", skill = 200, reagents = { {"Bronze Framework",1}, {"Iron Strut",4}, {"Gyrochronatom",4}, {"Citrine",2}, {"Fused Wiring",1} } },  -- item 4396
    ["Mechanical Repair Kit"] = { prof = "Engineering", skill = 200, reagents = { {"Mithril Bar",1}, {"Mageweave Cloth",1}, {"Solid Blasting Powder",1} } },  -- item 11590
    ["Mechanical Squirrel"] = { prof = "Engineering", skill = 75, reagents = { {"Copper Modulator",1}, {"Handful of Copper Bolts",1}, {"Copper Bar",1}, {"Malachite",2} } },  -- item 4401
    ["Minor Recombobulator"] = { prof = "Engineering", skill = 140, reagents = { {"Bronze Tube",1}, {"Whirring Bronze Gizmo",2}, {"Medium Leather",2}, {"Moss Agate",1} } },  -- item 4381
    ["Mithril Blunderbuss"] = { prof = "Engineering", skill = 205, reagents = { {"Mithril Tube",1}, {"Unstable Trigger",1}, {"Heavy Stock",1}, {"Mithril Bar",4}, {"Elemental Fire",2} } },  -- item 10508
    ["Mithril Casing"] = { prof = "Engineering", skill = 215, reagents = { {"Mithril Bar",3} } },  -- item 10561
    ["Mithril Frag Bomb"] = { prof = "Engineering", skill = 215, reagents = { {"Mithril Casing",1}, {"Unstable Trigger",1}, {"Solid Blasting Powder",1} } },  -- item 10514
    ["Mithril Gyro-Shot"] = { prof = "Engineering", skill = 245, reagents = { {"Mithril Bar",2}, {"Solid Blasting Powder",2} } },  -- item 10513
    ["Mithril Heavy-bore Rifle"] = { prof = "Engineering", skill = 220, reagents = { {"Mithril Tube",2}, {"Unstable Trigger",1}, {"Heavy Stock",1}, {"Mithril Bar",6}, {"Citrine",2} } },  -- item 10510
    ["Mithril Mechanical Dragonling"] = { prof = "Engineering", skill = 250, reagents = { {"Mithril Bar",14}, {"Heart of Fire",4}, {"Truesilver Bar",4}, {"Inlaid Mithril Cylinder",2}, {"Goblin Rocket Fuel",2}, {"Star Ruby",2} } },  -- item 10576
    ["Mithril Tube"] = { prof = "Engineering", skill = 195, reagents = { {"Mithril Bar",3} } },  -- item 10559
    ["Mooncloth"] = { prof = "Tailoring", skill = 250, reagents = { {"Felcloth",2} } },  -- item 14342
    ["Mooncloth Bag"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",4}, {"Mooncloth",1}, {"Rune Thread",1} } },  -- item 14155
    ["Mooncloth Boots"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",6}, {"Mooncloth",4}, {"Black Pearl",2}, {"Rune Thread",1} } },  -- item 15802
    ["Mooncloth Circlet"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",4}, {"Mooncloth",6}, {"Azerothian Diamond",1}, {"Enchanted Leather",2}, {"Rune Thread",2} } },  -- item 14140
    ["Mooncloth Gloves"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Mooncloth",6}, {"Golden Pearl",2}, {"Rune Thread",2} } },  -- item 18409
    ["Mooncloth Leggings"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",6}, {"Mooncloth",4}, {"Rune Thread",1} } },  -- item 14137
    ["Mooncloth Robe"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",6}, {"Mooncloth",4}, {"Golden Pearl",2}, {"Rune Thread",2} } },  -- item 18486
    ["Mooncloth Shoulders"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",5}, {"Mooncloth",5}, {"Rune Thread",1} } },  -- item 14139
    ["Mooncloth Vest"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",6}, {"Mooncloth",4}, {"Rune Thread",1} } },  -- item 14138
    ["Moonsight Rifle"] = { prof = "Engineering", skill = 145, reagents = { {"Bronze Tube",3}, {"Whirring Bronze Gizmo",3}, {"Heavy Stock",1}, {"Lesser Moonstone",2} } },  -- item 4383
    ["Orange Mageweave Shirt"] = { prof = "Tailoring", skill = 215, reagents = { {"Bolt of Mageweave",1}, {"Orange Dye",1}, {"Heavy Silken Thread",1} } },  -- item 10056
    ["Orange Martial Shirt"] = { prof = "Tailoring", skill = 220, reagents = { {"Bolt of Mageweave",2}, {"Orange Dye",2}, {"Heavy Silken Thread",1} } },  -- item 10052
    ["Ornate Spyglass"] = { prof = "Engineering", skill = 135, reagents = { {"Bronze Tube",2}, {"Whirring Bronze Gizmo",2}, {"Copper Modulator",1}, {"Moss Agate",1} } },  -- item 5507
    ["Parachute Cloak"] = { prof = "Engineering", skill = 225, reagents = { {"Bolt of Mageweave",4}, {"Shadow Silk",2}, {"Unstable Trigger",1}, {"Solid Blasting Powder",4} } },  -- item 10518
    ["Pearl-clasped Cloak"] = { prof = "Tailoring", skill = 90, reagents = { {"Bolt of Woolen Cloth",3}, {"Fine Thread",2}, {"Small Lustrous Pearl",1} } },  -- item 5542
    ["Pet Bombling"] = { prof = "Engineering", skill = 205, reagents = { {"Big Iron Bomb",1}, {"Heart of Fire",1}, {"Fused Wiring",1}, {"Mithril Bar",6} } },  -- item 11825
    ["Phoenix Gloves"] = { prof = "Tailoring", skill = 125, reagents = { {"Bolt of Woolen Cloth",4}, {"Iridescent Pearl",1}, {"Fine Thread",4}, {"Bleach",2} } },  -- item 4331
    ["Phoenix Pants"] = { prof = "Tailoring", skill = 125, reagents = { {"Bolt of Woolen Cloth",6}, {"Iridescent Pearl",1}, {"Fine Thread",3} } },  -- item 4317
    ["Pink Mageweave Shirt"] = { prof = "Tailoring", skill = 235, reagents = { {"Bolt of Mageweave",3}, {"Pink Dye",1}, {"Heavy Silken Thread",1} } },  -- item 10055
    ["Portable Bronze Mortar"] = { prof = "Engineering", skill = 165, reagents = { {"Bronze Tube",4}, {"Iron Strut",1}, {"Heavy Blasting Powder",4}, {"Medium Leather",4} } },  -- item 4403
    ["Powerful Seaforium Charge"] = { prof = "Engineering", skill = 275, reagents = { {"Thorium Widget",2}, {"Dense Blasting Powder",3}, {"Rugged Leather",2}, {"Refreshing Spring Water",1} } },  -- item 18594
    ["Practice Lock"] = { prof = "Engineering", skill = 100, reagents = { {"Bronze Bar",1}, {"Handful of Copper Bolts",2}, {"Weak Flux",1} } },  -- item 6712
    ["Red Firework"] = { prof = "Engineering", skill = 150, reagents = { {"Heavy Blasting Powder",1}, {"Heavy Leather",1} } },  -- item 9318
    ["Red Linen Bag"] = { prof = "Tailoring", skill = 70, reagents = { {"Bolt of Linen Cloth",4}, {"Fine Thread",1}, {"Red Dye",1} } },  -- item 5762
    ["Red Linen Robe"] = { prof = "Tailoring", skill = 40, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",2}, {"Red Dye",2} } },  -- item 2572
    ["Red Linen Shirt"] = { prof = "Tailoring", skill = 40, reagents = { {"Bolt of Linen Cloth",2}, {"Coarse Thread",1}, {"Red Dye",1} } },  -- item 2575
    ["Red Linen Vest"] = { prof = "Tailoring", skill = 55, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",1}, {"Red Dye",1} } },  -- item 6239
    ["Red Mageweave Bag"] = { prof = "Tailoring", skill = 235, reagents = { {"Bolt of Mageweave",4}, {"Red Dye",2}, {"Heavy Silken Thread",2} } },  -- item 10051
    ["Red Mageweave Gloves"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",3}, {"Red Dye",2}, {"Heavy Silken Thread",2} } },  -- item 10018
    ["Red Mageweave Headband"] = { prof = "Tailoring", skill = 240, reagents = { {"Bolt of Mageweave",4}, {"Red Dye",2}, {"Heavy Silken Thread",2} } },  -- item 10033
    ["Red Mageweave Pants"] = { prof = "Tailoring", skill = 215, reagents = { {"Bolt of Mageweave",3}, {"Red Dye",2}, {"Heavy Silken Thread",1} } },  -- item 10009
    ["Red Mageweave Shoulders"] = { prof = "Tailoring", skill = 235, reagents = { {"Bolt of Mageweave",4}, {"Red Dye",2}, {"Heavy Silken Thread",3} } },  -- item 10029
    ["Red Mageweave Vest"] = { prof = "Tailoring", skill = 215, reagents = { {"Bolt of Mageweave",3}, {"Red Dye",2}, {"Heavy Silken Thread",1} } },  -- item 10007
    ["Red Rocket Cluster"] = { prof = "Engineering", skill = 225, reagents = { {"Solid Blasting Powder",1}, {"Thick Leather",1} } },  -- item 21576
    ["Red Swashbuckler's Shirt"] = { prof = "Tailoring", skill = 175, reagents = { {"Bolt of Silk Cloth",3}, {"Red Dye",2}, {"Silken Thread",1} } },  -- item 6796
    ["Red Woolen Bag"] = { prof = "Tailoring", skill = 115, reagents = { {"Bolt of Woolen Cloth",4}, {"Red Dye",1}, {"Fine Thread",1} } },  -- item 5763
    ["Red Woolen Boots"] = { prof = "Tailoring", skill = 95, reagents = { {"Bolt of Woolen Cloth",4}, {"Light Leather",2}, {"Fine Thread",1}, {"Red Dye",2} } },  -- item 4313
    ["Reinforced Linen Cape"] = { prof = "Tailoring", skill = 60, reagents = { {"Bolt of Linen Cloth",2}, {"Coarse Thread",3} } },  -- item 2580
    ["Reinforced Woolen Shoulders"] = { prof = "Tailoring", skill = 120, reagents = { {"Bolt of Woolen Cloth",6}, {"Medium Leather",2}, {"Fine Thread",2} } },  -- item 4315
    ["Rich Purple Silk Shirt"] = { prof = "Tailoring", skill = 185, reagents = { {"Bolt of Silk Cloth",4}, {"Purple Dye",1}, {"Silken Thread",1} } },  -- item 4335
    ["Robe of Power"] = { prof = "Tailoring", skill = 190, reagents = { {"Bolt of Mageweave",2}, {"Elemental Earth",2}, {"Elemental Water",2}, {"Elemental Fire",2}, {"Elemental Air",2}, {"Silken Thread",2} } },  -- item 7054
    ["Robe of the Archmage"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Essence of Fire",10}, {"Essence of Air",10}, {"Essence of Earth",10}, {"Essence of Water",10}, {"Rune Thread",2} } },  -- item 14152
    ["Robe of the Void"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Demonic Rune",20}, {"Felcloth",40}, {"Essence of Fire",12}, {"Essence of Undeath",12}, {"Rune Thread",2} } },  -- item 14153
    ["Robe of Winter Night"] = { prof = "Tailoring", skill = 285, reagents = { {"Bolt of Runecloth",10}, {"Felcloth",12}, {"Essence of Undeath",4}, {"Essence of Water",4}, {"Rune Thread",1} } },  -- item 14136
    ["Robes of Arcana"] = { prof = "Tailoring", skill = 150, reagents = { {"Bolt of Silk Cloth",4}, {"Fine Thread",2}, {"Spider's Silk",2} } },  -- item 5770
    ["Rose Colored Goggles"] = { prof = "Engineering", skill = 230, reagents = { {"Thick Leather",6}, {"Star Ruby",2} } },  -- item 10503
    ["Rough Blasting Powder"] = { prof = "Engineering", skill = 1, reagents = { {"Rough Stone",1} } },  -- item 4357
    ["Rough Boomstick"] = { prof = "Engineering", skill = 50, reagents = { {"Copper Tube",1}, {"Handful of Copper Bolts",1}, {"Wooden Stock",1} } },  -- item 4362
    ["Rough Copper Bomb"] = { prof = "Engineering", skill = 30, reagents = { {"Copper Bar",1}, {"Handful of Copper Bolts",1}, {"Rough Blasting Powder",2}, {"Linen Cloth",1} } },  -- item 4360
    ["Rough Dynamite"] = { prof = "Engineering", skill = 1, reagents = { {"Rough Blasting Powder",2}, {"Linen Cloth",1} } },  -- item 4358
    ["Runecloth Bag"] = { prof = "Tailoring", skill = 260, reagents = { {"Bolt of Runecloth",5}, {"Rugged Leather",2}, {"Rune Thread",1} } },  -- item 14046
    ["Runecloth Belt"] = { prof = "Tailoring", skill = 255, reagents = { {"Bolt of Runecloth",3}, {"Rune Thread",1} } },  -- item 13856
    ["Runecloth Boots"] = { prof = "Tailoring", skill = 280, reagents = { {"Bolt of Runecloth",4}, {"Ironweb Spider Silk",2}, {"Rugged Leather",4}, {"Rune Thread",1} } },  -- item 13864
    ["Runecloth Cloak"] = { prof = "Tailoring", skill = 265, reagents = { {"Bolt of Runecloth",4}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 13860
    ["Runecloth Gloves"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",4}, {"Rugged Leather",4}, {"Rune Thread",1} } },  -- item 13863
    ["Runecloth Headband"] = { prof = "Tailoring", skill = 295, reagents = { {"Bolt of Runecloth",4}, {"Ironweb Spider Silk",2}, {"Rune Thread",1} } },  -- item 13866
    ["Runecloth Pants"] = { prof = "Tailoring", skill = 285, reagents = { {"Bolt of Runecloth",6}, {"Ironweb Spider Silk",2}, {"Rune Thread",1} } },  -- item 13865
    ["Runecloth Robe"] = { prof = "Tailoring", skill = 260, reagents = { {"Bolt of Runecloth",5}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 13858
    ["Runecloth Shoulders"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",7}, {"Ironweb Spider Silk",2}, {"Rugged Leather",4}, {"Rune Thread",1} } },  -- item 13867
    ["Runecloth Tunic"] = { prof = "Tailoring", skill = 260, reagents = { {"Bolt of Runecloth",5}, {"Ironweb Spider Silk",1}, {"Rune Thread",1} } },  -- item 13857
    ["Runed Stygian Belt"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",2}, {"Dark Rune",6}, {"Felcloth",2}, {"Enchanted Leather",2}, {"Ironweb Spider Silk",2} } },  -- item 20539
    ["Runed Stygian Boots"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",4}, {"Dark Rune",6}, {"Felcloth",4}, {"Enchanted Leather",2}, {"Ironweb Spider Silk",2} } },  -- item 20537
    ["Runed Stygian Leggings"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",6}, {"Dark Rune",8}, {"Felcloth",6}, {"Ironweb Spider Silk",2} } },  -- item 20538
    ["Salt Shaker"] = { prof = "Engineering", skill = 250, reagents = { {"Mithril Casing",1}, {"Thorium Bar",6}, {"Gold Power Core",1}, {"Unstable Trigger",4} } },  -- item 15846
    ["Satchel of Cenarius"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",6}, {"Mooncloth",2}, {"Black Lotus",1}, {"Ironweb Spider Silk",4} } },  -- item 22252
    ["Shadow Goggles"] = { prof = "Engineering", skill = 120, reagents = { {"Medium Leather",4}, {"Shadowgem",2} } },  -- item 4373
    ["Shadow Hood"] = { prof = "Tailoring", skill = 170, reagents = { {"Bolt of Silk Cloth",4}, {"Silken Thread",1}, {"Shadow Oil",1} } },  -- item 4323
    ["Shadoweave Boots"] = { prof = "Tailoring", skill = 240, reagents = { {"Bolt of Mageweave",6}, {"Shadow Silk",6}, {"Heavy Silken Thread",3}, {"Thick Leather",2} } },  -- item 10031
    ["Shadoweave Gloves"] = { prof = "Tailoring", skill = 225, reagents = { {"Bolt of Mageweave",5}, {"Shadow Silk",5}, {"Heavy Silken Thread",2} } },  -- item 10023
    ["Shadoweave Mask"] = { prof = "Tailoring", skill = 245, reagents = { {"Bolt of Mageweave",2}, {"Shadow Silk",8}, {"Heavy Silken Thread",2} } },  -- item 10025
    ["Shadoweave Pants"] = { prof = "Tailoring", skill = 210, reagents = { {"Bolt of Mageweave",3}, {"Shadow Silk",2}, {"Heavy Silken Thread",1} } },  -- item 10002
    ["Shadoweave Robe"] = { prof = "Tailoring", skill = 215, reagents = { {"Bolt of Mageweave",3}, {"Shadow Silk",2}, {"Heavy Silken Thread",1} } },  -- item 10004
    ["Shadoweave Shoulders"] = { prof = "Tailoring", skill = 235, reagents = { {"Bolt of Mageweave",5}, {"Shadow Silk",4}, {"Heavy Silken Thread",2} } },  -- item 10028
    ["Silk Headband"] = { prof = "Tailoring", skill = 160, reagents = { {"Bolt of Silk Cloth",3}, {"Fine Thread",2} } },  -- item 7050
    ["Silver Contact"] = { prof = "Engineering", skill = 90, reagents = { {"Silver Bar",1} } },  -- item 4404
    ["Silver-plated Shotgun"] = { prof = "Engineering", skill = 130, reagents = { {"Bronze Tube",2}, {"Whirring Bronze Gizmo",2}, {"Heavy Stock",1}, {"Silver Bar",3} } },  -- item 4379
    ["Simple Black Dress"] = { prof = "Tailoring", skill = 235, reagents = { {"Bolt of Mageweave",3}, {"Black Dye",1}, {"Heavy Silken Thread",1}, {"Bleach",1} } },  -- item 10053
    ["Simple Dress"] = { prof = "Tailoring", skill = 40, reagents = { {"Bolt of Linen Cloth",2}, {"Coarse Thread",1}, {"Blue Dye",1}, {"Bleach",1} } },  -- item 6786
    ["Simple Kilt"] = { prof = "Tailoring", skill = 75, reagents = { {"Bolt of Linen Cloth",4}, {"Fine Thread",1} } },  -- item 10047
    ["Simple Linen Boots"] = { prof = "Tailoring", skill = 20, reagents = { {"Bolt of Linen Cloth",2}, {"Light Leather",1}, {"Coarse Thread",1} } },  -- item 10046
    ["Simple Linen Pants"] = { prof = "Tailoring", skill = 1, reagents = { {"Bolt of Linen Cloth",1}, {"Coarse Thread",1} } },  -- item 10045
    ["Small Blue Rocket"] = { prof = "Engineering", skill = 125, reagents = { {"Coarse Blasting Powder",1}, {"Medium Leather",1} } },  -- item 21558
    ["Small Bronze Bomb"] = { prof = "Engineering", skill = 120, reagents = { {"Coarse Blasting Powder",4}, {"Bronze Bar",2}, {"Silver Contact",1}, {"Wool Cloth",1} } },  -- item 4374
    ["Small Green Rocket"] = { prof = "Engineering", skill = 125, reagents = { {"Coarse Blasting Powder",1}, {"Medium Leather",1} } },  -- item 21559
    ["Small Red Rocket"] = { prof = "Engineering", skill = 125, reagents = { {"Coarse Blasting Powder",1}, {"Medium Leather",1} } },  -- item 21557
    ["Small Seaforium Charge"] = { prof = "Engineering", skill = 100, reagents = { {"Coarse Blasting Powder",2}, {"Copper Modulator",1}, {"Light Leather",1}, {"Refreshing Spring Water",1} } },  -- item 4367
    ["Small Silk Pack"] = { prof = "Tailoring", skill = 150, reagents = { {"Bolt of Silk Cloth",3}, {"Heavy Leather",2}, {"Fine Thread",3} } },  -- item 4245
    ["Snake Burst Firework"] = { prof = "Engineering", skill = 250, reagents = { {"Dense Blasting Powder",2}, {"Runecloth",2}, {"Deeprock Salt",1} } },  -- item 19026
    ["Sniper Scope"] = { prof = "Engineering", skill = 240, reagents = { {"Mithril Tube",1}, {"Star Ruby",1}, {"Truesilver Bar",2} } },  -- item 10548
    ["SnowMaster 9000"] = { prof = "Engineering", skill = 190, reagents = { {"Mithril Bar",8}, {"Gyrochronatom",4}, {"Snowball",4}, {"Frost Oil",1} } },  -- item 17716
    ["Soft-soled Linen Boots"] = { prof = "Tailoring", skill = 80, reagents = { {"Bolt of Linen Cloth",5}, {"Light Leather",2}, {"Fine Thread",1} } },  -- item 4312
    ["Solid Blasting Powder"] = { prof = "Engineering", skill = 175, reagents = { {"Solid Stone",2} } },  -- item 10505
    ["Solid Dynamite"] = { prof = "Engineering", skill = 175, reagents = { {"Solid Blasting Powder",1}, {"Silk Cloth",1} } },  -- item 10507
    ["Soul Pouch"] = { prof = "Tailoring", skill = 260, reagents = { {"Bolt of Runecloth",6}, {"Rugged Leather",4}, {"Ichor of Undeath",2}, {"Rune Thread",1} } },  -- item 21340
    ["Spellpower Goggles Xtreme"] = { prof = "Engineering", skill = 225, reagents = { {"Thick Leather",4}, {"Star Ruby",2} } },  -- item 10502
    ["Spellpower Goggles Xtreme Plus"] = { prof = "Engineering", skill = 270, reagents = { {"Spellpower Goggles Xtreme",1}, {"Star Ruby",4}, {"Enchanted Leather",2}, {"Runecloth",8} } },  -- item 15999
    ["Spider Belt"] = { prof = "Tailoring", skill = 180, reagents = { {"Bolt of Silk Cloth",4}, {"Thick Spider's Silk",2}, {"Iron Buckle",1} } },  -- item 4328
    ["Spider Silk Slippers"] = { prof = "Tailoring", skill = 140, reagents = { {"Bolt of Silk Cloth",3}, {"Spider's Silk",1}, {"Fine Thread",2} } },  -- item 4321
    ["Spidersilk Boots"] = { prof = "Tailoring", skill = 125, reagents = { {"Bolt of Silk Cloth",2}, {"Medium Leather",4}, {"Spider's Silk",4}, {"Iridescent Pearl",2} } },  -- item 4320
    ["Standard Scope"] = { prof = "Engineering", skill = 110, reagents = { {"Bronze Tube",1}, {"Moss Agate",1} } },  -- item 4406
    ["Star Belt"] = { prof = "Tailoring", skill = 200, reagents = { {"Bolt of Mageweave",4}, {"Heavy Leather",4}, {"Citrine",1}, {"Iron Buckle",1}, {"Silken Thread",1} } },  -- item 4329
    ["Steam Tonk Controller"] = { prof = "Engineering", skill = 275, reagents = { {"Thorium Widget",2}, {"Mithril Casing",1}, {"Gold Power Core",1} } },  -- item 22728
    ["Stylish Blue Shirt"] = { prof = "Tailoring", skill = 120, reagents = { {"Bolt of Woolen Cloth",4}, {"Blue Dye",2}, {"Gray Dye",1}, {"Fine Thread",1} } },  -- item 6384
    ["Stylish Green Shirt"] = { prof = "Tailoring", skill = 120, reagents = { {"Bolt of Woolen Cloth",4}, {"Green Dye",2}, {"Gray Dye",1}, {"Fine Thread",1} } },  -- item 6385
    ["Stylish Red Shirt"] = { prof = "Tailoring", skill = 110, reagents = { {"Bolt of Woolen Cloth",3}, {"Red Dye",2}, {"Fine Thread",1} } },  -- item 4330
    ["Sylvan Crown"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",4}, {"Mooncloth",2}, {"Living Essence",2}, {"Ironweb Spider Silk",2} } },  -- item 22757
    ["Sylvan Shoulders"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",2}, {"Living Essence",4}, {"Ironweb Spider Silk",2} } },  -- item 22758
    ["Sylvan Vest"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",4}, {"Bloodvine",2}, {"Living Essence",2}, {"Ironweb Spider Silk",2} } },  -- item 22756
    ["Target Dummy"] = { prof = "Engineering", skill = 85, reagents = { {"Copper Modulator",1}, {"Handful of Copper Bolts",2}, {"Bronze Bar",1}, {"Wool Cloth",1} } },  -- item 4366
    ["The Big One"] = { prof = "Engineering", skill = 235, reagents = { {"Mithril Casing",1}, {"Goblin Rocket Fuel",1}, {"Solid Dynamite",6}, {"Unstable Trigger",1} } },  -- item 10586
    ["Thorium Grenade"] = { prof = "Engineering", skill = 260, reagents = { {"Thorium Widget",1}, {"Thorium Bar",3}, {"Dense Blasting Powder",3}, {"Runecloth",3} } },  -- item 15993
    ["Thorium Rifle"] = { prof = "Engineering", skill = 260, reagents = { {"Mithril Tube",2}, {"Mithril Casing",2}, {"Thorium Widget",2}, {"Thorium Bar",4}, {"Deadly Scope",1} } },  -- item 15995
    ["Thorium Shells"] = { prof = "Engineering", skill = 285, reagents = { {"Thorium Bar",2}, {"Dense Blasting Powder",1} } },  -- item 15997
    ["Thorium Tube"] = { prof = "Engineering", skill = 275, reagents = { {"Thorium Bar",6} } },  -- item 16000
    ["Thorium Widget"] = { prof = "Engineering", skill = 260, reagents = { {"Thorium Bar",3}, {"Runecloth",1} } },  -- item 15994
    ["Tranquil Mechanical Yeti"] = { prof = "Engineering", skill = 250, reagents = { {"Cured Rugged Hide",1}, {"Thorium Widget",4}, {"Globe of Water",2}, {"Truesilver Transformer",2}, {"Gold Power Core",1} } },  -- item 21277
    ["Truefaith Gloves"] = { prof = "Tailoring", skill = 150, reagents = { {"Bolt of Silk Cloth",3}, {"Heavy Leather",2}, {"Healing Potion",4}, {"Fine Thread",1} } },  -- item 7049
    ["Truefaith Vestments"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",12}, {"Mooncloth",10}, {"Righteous Orb",4}, {"Golden Pearl",4}, {"Ghost Dye",10}, {"Rune Thread",2} } },  -- item 14154
    ["Truesilver Transformer"] = { prof = "Engineering", skill = 260, reagents = { {"Truesilver Bar",2}, {"Elemental Earth",2}, {"Elemental Air",1} } },  -- item 18631
    ["Tuxedo Jacket"] = { prof = "Tailoring", skill = 250, reagents = { {"Bolt of Mageweave",5}, {"Heavy Silken Thread",3} } },  -- item 10036
    ["Tuxedo Pants"] = { prof = "Tailoring", skill = 245, reagents = { {"Bolt of Mageweave",4}, {"Heavy Silken Thread",3} } },  -- item 10035
    ["Tuxedo Shirt"] = { prof = "Tailoring", skill = 240, reagents = { {"Bolt of Mageweave",4}, {"Heavy Silken Thread",2} } },  -- item 10034
    ["Ultra-Flash Shadow Reflector"] = { prof = "Engineering", skill = 300, reagents = { {"Dark Iron Bar",8}, {"Truesilver Transformer",4}, {"Living Essence",6}, {"Essence of Undeath",4}, {"Azerothian Diamond",2}, {"Large Opal",2} } },  -- item 18639
    ["Ultrasafe Transporter - Gadgetzan"] = { prof = "Engineering", skill = 285, reagents = { {"Mithril Bar",12}, {"Truesilver Transformer",2}, {"Core of Earth",4}, {"Globe of Water",2}, {"Aquamarine",4}, {"Inlaid Mithril Cylinder",1} } },  -- item 18986
    ["Unstable Trigger"] = { prof = "Engineering", skill = 200, reagents = { {"Mithril Bar",1}, {"Mageweave Cloth",1}, {"Solid Blasting Powder",1} } },  -- item 10560
    ["Voice Amplification Modulator"] = { prof = "Engineering", skill = 290, reagents = { {"Delicate Arcanite Converter",2}, {"Gold Power Core",1}, {"Thorium Widget",1}, {"Large Opal",1} } },  -- item 16009
    ["Whirring Bronze Gizmo"] = { prof = "Engineering", skill = 125, reagents = { {"Bronze Bar",2}, {"Wool Cloth",1} } },  -- item 4375
    ["White Bandit Mask"] = { prof = "Tailoring", skill = 215, reagents = { {"Bolt of Mageweave",1}, {"Bleach",1}, {"Heavy Silken Thread",1} } },  -- item 10008
    ["White Linen Robe"] = { prof = "Tailoring", skill = 30, reagents = { {"Bolt of Linen Cloth",3}, {"Coarse Thread",1}, {"Bleach",1} } },  -- item 6241
    ["White Linen Shirt"] = { prof = "Tailoring", skill = 1, reagents = { {"Bolt of Linen Cloth",1}, {"Coarse Thread",1}, {"Bleach",1} } },  -- item 2576
    ["White Swashbuckler's Shirt"] = { prof = "Tailoring", skill = 160, reagents = { {"Bolt of Silk Cloth",3}, {"Bleach",2}, {"Silken Thread",1} } },  -- item 6795
    ["White Wedding Dress"] = { prof = "Tailoring", skill = 250, reagents = { {"Bolt of Mageweave",5}, {"Heavy Silken Thread",3}, {"Bleach",1} } },  -- item 10040
    ["White Woolen Dress"] = { prof = "Tailoring", skill = 110, reagents = { {"Bolt of Woolen Cloth",3}, {"Bleach",4}, {"Fine Thread",1} } },  -- item 6787
    ["Wisdom of the Timbermaw"] = { prof = "Tailoring", skill = 290, reagents = { {"Bolt of Runecloth",8}, {"Essence of Earth",3}, {"Living Essence",3}, {"Ironweb Spider Silk",2} } },  -- item 19047
    ["Wizardweave Leggings"] = { prof = "Tailoring", skill = 275, reagents = { {"Bolt of Runecloth",6}, {"Dream Dust",1}, {"Rune Thread",1} } },  -- item 14132
    ["Wizardweave Robe"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",8}, {"Dream Dust",2}, {"Rune Thread",1} } },  -- item 14128
    ["Wizardweave Turban"] = { prof = "Tailoring", skill = 300, reagents = { {"Bolt of Runecloth",6}, {"Dream Dust",4}, {"Star Ruby",1}, {"Rune Thread",1} } },  -- item 14130
    ["Woolen Bag"] = { prof = "Tailoring", skill = 80, reagents = { {"Bolt of Woolen Cloth",3}, {"Fine Thread",1} } },  -- item 4240
    ["Woolen Boots"] = { prof = "Tailoring", skill = 95, reagents = { {"Bolt of Woolen Cloth",4}, {"Fine Thread",2}, {"Light Leather",2} } },  -- item 2583
    ["Woolen Cape"] = { prof = "Tailoring", skill = 75, reagents = { {"Bolt of Woolen Cloth",1}, {"Fine Thread",1} } },  -- item 2584
    ["World Enlarger"] = { prof = "Engineering", skill = 260, reagents = { {"Mithril Casing",1}, {"Thorium Widget",2}, {"Gold Power Core",1}, {"Unstable Trigger",1}, {"Citrine",1} } },  -- item 18660
}
