-- AUTO-GENERATED by tools/build_mining.py. DO NOT EDIT BY HAND.
-- Smelting (bars) + mining-node stone by-products, for DropChanceTooltip material aggregation.
DropChanceTooltip_MiningBars = {
    ["Bronze Bar"] = { skill = 65, reagents = { {"Copper Bar",1}, {"Tin Bar",1} } },  -- item 2841
    ["Copper Bar"] = { skill = 1, reagents = { {"Copper Ore",1} } },  -- item 2840
    ["Dark Iron Bar"] = { skill = 230, reagents = { {"Dark Iron Ore",8} } },  -- item 11371
    ["Elementium Bar"] = { skill = 300, reagents = { {"Elementium Ore",1}, {"Arcanite Bar",10}, {"Fiery Core",1}, {"Elemental Flux",3} } },  -- item 17771
    ["Gold Bar"] = { skill = 155, reagents = { {"Gold Ore",1} } },  -- item 3577
    ["Iron Bar"] = { skill = 125, reagents = { {"Iron Ore",1} } },  -- item 3575
    ["Mithril Bar"] = { skill = 175, reagents = { {"Mithril Ore",1} } },  -- item 3860
    ["Silver Bar"] = { skill = 75, reagents = { {"Silver Ore",1} } },  -- item 2842
    ["Steel Bar"] = { skill = 165, reagents = { {"Iron Bar",1}, {"Coal",1} } },  -- item 3859
    ["Thorium Bar"] = { skill = 250, reagents = { {"Thorium Ore",1} } },  -- item 12359
    ["Tin Bar"] = { skill = 65, reagents = { {"Tin Ore",1} } },  -- item 3576
    ["Truesilver Bar"] = { skill = 230, reagents = { {"Truesilver Ore",1} } },  -- item 6037
}
DropChanceTooltip_MiningStone = {
    ["Coarse Stone"] = { min = 65, max = 125, ores = { "Tin Ore" } },  -- item 2836
    ["Dense Stone"] = { min = 245, max = 300, ores = { "Thorium Ore" } },  -- item 12365
    ["Heavy Stone"] = { min = 125, max = 175, ores = { "Iron Ore" } },  -- item 2838
    ["Rough Stone"] = { min = 1, max = 65, ores = { "Copper Ore" } },  -- item 2835
    ["Solid Stone"] = { min = 175, max = 245, ores = { "Mithril Ore" } },  -- item 7912
}
