-- AUTO-GENERATED by tools/build_skinning.py. DO NOT EDIT BY HAND.
-- Leather/hide item -> normal-beast level range { min, max }. Classic skinning is unchanged on Forever.
DropChanceTooltip_SkinningLevels = {
    [783] = { 11, 21 },  -- Light Hide
    [2318] = { 11, 23 },  -- Light Leather
    [2319] = { 21, 36 },  -- Medium Leather
    [2934] = { 5, 17 },  -- Ruined Leather Scraps
    [4232] = { 21, 36 },  -- Medium Hide
    [4234] = { 30, 46 },  -- Heavy Leather
    [4235] = { 32, 43 },  -- Heavy Hide
    [4304] = { 40, 55 },  -- Thick Leather
    [8169] = { 40, 58 },  -- Thick Hide
    [8170] = { 47, 60 },  -- Rugged Leather
    [8171] = { 50, 60 },  -- Rugged Hide
}
