-- AUTO-GENERATED by tools/wowhead_scrape.py --skinning. DO NOT EDIT BY HAND.
-- Leather/hide item -> creatures you skin it from (npc ids). Level range resolved at runtime via
-- Data/MobLevels.lua. Placeholder until the scrape runs: `python3 tools/wowhead_scrape.py --skinning`.
DropChanceTooltip_SkinningSources = {
}
