#!/usr/bin/env python3
"""
Convert a JSON array of Classic alchemy recipes into the bundled Data/AlchemyRecipes.lua table used by
DropChanceTooltip's material aggregation (a potion/elixir hover shows "Crafted  Alchemy <skill>", with
reagents behind Shift later).

Input JSON (from the compile step): array of objects
  {"name":"Elixir of Minor Defense","itemID":5997,"skill":60,
   "reagents":[{"name":"Bruiseweed","count":1},{"name":"Empty Vial","count":1}]}

Output: Data/AlchemyRecipes.lua ->
  DropChanceTooltip_AlchemyRecipes = {
    ["Elixir of Minor Defense"] = { skill = 60, reagents = { {"Bruiseweed",1}, {"Empty Vial",1} } },
  }
Keyed by crafted item NAME (the addon matches GetItemInfo(name)). itemID kept as a trailing comment.

Usage:
    python3 tools/build_alchemy.py recipes.json          # file
    python3 tools/build_alchemy.py < recipes.json        # stdin
    python3 tools/build_alchemy.py --selftest
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCRIPT_DIR, "..", "Data", "AlchemyRecipes.lua")


def _lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_lua(recipes):
    lines = [
        "-- AUTO-GENERATED by tools/build_alchemy.py. DO NOT EDIT BY HAND.",
        "-- Classic (1-300) alchemy recipes: crafted item name -> { skill, reagents={ {name,count},... } }.",
        "-- Used by DropChanceTooltip material aggregation (potion/elixir -> \"Alchemy <skill>\").",
        "DropChanceTooltip_AlchemyRecipes = {",
    ]
    seen = set()
    for r in sorted(recipes, key=lambda x: (x.get("name") or "").lower()):
        name = r.get("name")
        if not name or name in seen:
            continue
        seen.add(name)
        skill = int(r.get("skill") or 0)
        reagents = r.get("reagents") or []
        rparts = []
        for rg in reagents:
            rn = rg.get("name") if isinstance(rg, dict) else (rg[0] if rg else None)
            rc = (rg.get("count") if isinstance(rg, dict) else (rg[1] if len(rg) > 1 else 1)) or 1
            if rn:
                rparts.append("{%s,%d}" % (_lua_str(rn), int(rc)))
        reag = (" reagents = { " + ", ".join(rparts) + " }") if rparts else ""
        comma = "," if reag else ""
        idc = ("  -- item %s" % r["itemID"]) if r.get("itemID") else ""
        lines.append("    [%s] = { skill = %d%s%s },%s" % (_lua_str(name), skill, comma, reag, idc))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    if "--selftest" in sys.argv:
        sample = [{"name": "Elixir of Minor Defense", "itemID": 5997, "skill": 60,
                   "reagents": [{"name": "Bruiseweed", "count": 1}, {"name": "Empty Vial", "count": 1}]}]
        out = emit_lua(sample)
        ok = '["Elixir of Minor Defense"] = { skill = 60,' in out and '{"Bruiseweed",1}' in out
        print(out)
        print("SELFTEST OK" if ok else "SELFTEST FAILED")
        return 0 if ok else 1

    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    text = open(args[0], encoding="utf-8").read() if args else sys.stdin.read()
    recipes = json.loads(text)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(emit_lua(recipes))
    print("wrote %s: %d recipes" % (os.path.relpath(OUT, SCRIPT_DIR), len(recipes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
