#!/usr/bin/env python3
"""
Convert compiled Classic mining data (smelting bars + stone-from-node) into Data/MiningProducts.lua
for DropChanceTooltip's material aggregation:
  - a metal BAR  -> "Smelted  Mining <skill>"  (+ ore reagents on Shift)
  - a STONE      -> "Mined    Mining <lo>-<hi>" (+ the ore nodes that drop it, on Shift)

Input JSON object:
  {"bars":[{"name":"Copper Bar","itemID":2840,"skill":1,"reagents":[{"name":"Copper Ore","count":1}]}],
   "stone":[{"name":"Rough Stone","itemID":2835,"nodes":[{"node":"Copper Vein","ore":"Copper Ore","skill":1}]}]}

Output: DropChanceTooltip_MiningBars[name]={skill,reagents={{n,c}}} and
        DropChanceTooltip_MiningStone[name]={min,max,ores={...}} (min/max derived from node skills).

Usage: python3 tools/build_mining.py mining.json   |   < mining.json   |   --selftest
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCRIPT_DIR, "..", "Data", "MiningProducts.lua")


def _s(x):
    return '"' + str(x).replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_lua(data):
    lines = [
        "-- AUTO-GENERATED by tools/build_mining.py. DO NOT EDIT BY HAND.",
        "-- Smelting (bars) + mining-node stone by-products, for DropChanceTooltip material aggregation.",
        "DropChanceTooltip_MiningBars = {",
    ]
    for r in sorted(data.get("bars", []), key=lambda x: (x.get("name") or "").lower()):
        name = r.get("name")
        if not name:
            continue
        rparts = []
        for rg in r.get("reagents") or []:
            rn = rg.get("name") if isinstance(rg, dict) else (rg[0] if rg else None)
            rc = (rg.get("count") if isinstance(rg, dict) else (rg[1] if len(rg) > 1 else 1)) or 1
            if rn:
                rparts.append("{%s,%d}" % (_s(rn), int(rc)))
        reag = (" reagents = { " + ", ".join(rparts) + " }") if rparts else ""
        comma = "," if reag else ""
        idc = ("  -- item %s" % r["itemID"]) if r.get("itemID") else ""
        lines.append("    [%s] = { skill = %d%s%s },%s" % (_s(name), int(r.get("skill") or 0), comma, reag, idc))
    lines.append("}")
    # Stone: min = the tier node's required skill; max = the FARMING WINDOW end = the next stone tier's
    # node skill (so Rough Stone reads 1-65, i.e. "your primary stone from mining 1 up to Tin at 65"),
    # or that stone's own highest node / 300 for the top tier.
    stones = []
    for r in data.get("stone", []):
        name = r.get("name")
        if not name:
            continue
        skills, ores = [], []
        for nd in r.get("nodes") or []:
            sk = nd.get("skill")
            if isinstance(sk, (int, float)):
                skills.append(int(sk))
            ore = nd.get("ore") or nd.get("node")
            if ore and ore not in ores:
                ores.append(ore)
        stones.append({"name": name, "lo": min(skills) if skills else 0,
                       "node_hi": max(skills) if skills else 0, "ores": ores, "itemID": r.get("itemID")})
    order = sorted(stones, key=lambda s: s["lo"])
    for i, s in enumerate(order):
        nxt = order[i + 1]["lo"] if i + 1 < len(order) else 300
        s["hi"] = max(s["node_hi"], nxt)   # window extends to the next tier (or its own top node)
    lines.append("DropChanceTooltip_MiningStone = {")
    for s in sorted(stones, key=lambda x: x["name"].lower()):
        oparts = ", ".join(_s(o) for o in s["ores"])
        idc = ("  -- item %s" % s["itemID"]) if s.get("itemID") else ""
        lines.append("    [%s] = { min = %d, max = %d, ores = { %s } },%s" % (_s(s["name"]), s["lo"], s["hi"], oparts, idc))
    lines.append("}")
    return "\n".join(lines) + "\n"


SAMPLE = {
    "bars": [{"name": "Bronze Bar", "itemID": 2841, "skill": 65,
              "reagents": [{"name": "Copper Bar", "count": 1}, {"name": "Tin Bar", "count": 1}]}],
    "stone": [
        {"name": "Rough Stone", "itemID": 2835, "nodes": [{"node": "Copper Vein", "ore": "Copper Ore", "skill": 1}]},
        {"name": "Coarse Stone", "itemID": 2836, "nodes": [{"node": "Tin Vein", "ore": "Tin Ore", "skill": 65}]}],
}


def main():
    if "--selftest" in sys.argv:
        out = emit_lua(SAMPLE)
        ok = ('["Bronze Bar"] = { skill = 65,' in out
              and '["Rough Stone"] = { min = 1, max = 65, ores = { "Copper Ore" } }' in out
              and '["Coarse Stone"] = { min = 65, max = 300, ores = { "Tin Ore" } }' in out)
        print(out)
        print("SELFTEST OK" if ok else "SELFTEST FAILED")
        return 0 if ok else 1
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    data = json.loads(open(args[0], encoding="utf-8").read() if args else sys.stdin.read())
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(emit_lua(data))
    print("wrote %s: %d bars, %d stones" % (os.path.relpath(OUT, SCRIPT_DIR),
                                            len(data.get("bars", [])), len(data.get("stone", []))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
