#!/usr/bin/env python3
"""
Convert compiled leather beast-level ranges into Data/SkinningLevels.lua for DropChanceTooltip:
a leather/hide item -> "Skinning . Beasts <min>-<max>".

Input JSON: [{"name":"Medium Leather","itemID":2319,"min":21,"max":36}, ...]
Output: DropChanceTooltip_SkinningLevels[itemID] = { min, max }

Usage: python3 tools/build_skinning.py leather.json  |  < leather.json  |  --selftest
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCRIPT_DIR, "..", "Data", "SkinningLevels.lua")


def emit_lua(rows):
    lines = [
        "-- AUTO-GENERATED by tools/build_skinning.py. DO NOT EDIT BY HAND.",
        "-- Leather/hide item -> normal-beast level range { min, max }. Classic skinning is unchanged on Forever.",
        "DropChanceTooltip_SkinningLevels = {",
    ]
    for r in sorted(rows, key=lambda x: int(x.get("itemID") or 0)):
        iid = r.get("itemID")
        if not iid:
            continue
        mn, mx = int(r.get("min") or 0), int(r.get("max") or 0)
        nm = ("  -- %s" % r["name"]) if r.get("name") else ""
        lines.append("    [%d] = { %d, %d },%s" % (int(iid), mn, mx, nm))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    if "--selftest" in sys.argv:
        out = emit_lua([{"name": "Medium Leather", "itemID": 2319, "min": 21, "max": 36}])
        ok = "[2319] = { 21, 36 },  -- Medium Leather" in out
        print(out)
        print("SELFTEST OK" if ok else "SELFTEST FAILED")
        return 0 if ok else 1
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    rows = json.loads(open(args[0], encoding="utf-8").read() if args else sys.stdin.read())
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(emit_lua(rows))
    print("wrote %s: %d leather items" % (os.path.relpath(OUT, SCRIPT_DIR), len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
