#!/usr/bin/env python3
"""
Convert compiled crafting recipes (Tailoring, Engineering, ... -- any profession that produces items)
into Data/CraftRecipes.lua for DropChanceTooltip: a crafted item -> "Crafted  <Profession> <skill>",
with reagents behind Shift.

Input JSON: array of {name, itemID?, prof, skill, reagents?[{name,count}]}. You can concatenate several
professions into one array (or pass multiple JSON files -- they're merged).

Output: DropChanceTooltip_CraftRecipes[name] = { prof, skill, reagents={ {n,c},... } }

Usage:
    python3 tools/build_crafts.py tailoring.json engineering.json
    python3 tools/build_crafts.py < recipes.json
    python3 tools/build_crafts.py --selftest
"""
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCRIPT_DIR, "..", "Data", "CraftRecipes.lua")


def _s(x):
    return '"' + str(x).replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_lua(recipes):
    lines = [
        "-- AUTO-GENERATED by tools/build_crafts.py. DO NOT EDIT BY HAND.",
        "-- Crafted item name -> { prof, skill, reagents }. Tailoring/Engineering/etc. Used by",
        "-- DropChanceTooltip material aggregation (crafted item -> \"Crafted  <Profession> <skill>\").",
        "DropChanceTooltip_CraftRecipes = {",
    ]
    seen = set()
    for r in sorted(recipes, key=lambda x: (x.get("name") or "").lower()):
        name, prof = r.get("name"), r.get("prof")
        if not name or not prof or name in seen:
            continue
        seen.add(name)
        rparts = []
        for rg in r.get("reagents") or []:
            rn = rg.get("name") if isinstance(rg, dict) else (rg[0] if rg else None)
            rc = (rg.get("count") if isinstance(rg, dict) else (rg[1] if len(rg) > 1 else 1)) or 1
            if rn:
                rparts.append("{%s,%d}" % (_s(rn), int(rc)))
        reag = (", reagents = { " + ", ".join(rparts) + " }") if rparts else ""
        idc = ("  -- item %s" % r["itemID"]) if r.get("itemID") else ""
        lines.append("    [%s] = { prof = %s, skill = %d%s },%s"
                     % (_s(name), _s(prof), int(r.get("skill") or 0), reag, idc))
    lines.append("}")
    return "\n".join(lines) + "\n", len(seen)


def main():
    if "--selftest" in sys.argv:
        out, n = emit_lua([{"name": "Bolt of Linen Cloth", "itemID": 2996, "prof": "Tailoring", "skill": 1,
                            "reagents": [{"name": "Linen Cloth", "count": 2}]}])
        ok = '["Bolt of Linen Cloth"] = { prof = "Tailoring", skill = 1, reagents = { {"Linen Cloth",2} } }' in out
        print(out)
        print("SELFTEST OK" if ok else "SELFTEST FAILED")
        return 0 if ok else 1
    files = [a for a in sys.argv[1:] if not a.startswith("--")]
    recipes = []
    if files:
        for f in files:
            recipes.extend(json.loads(open(f, encoding="utf-8").read()))
    else:
        recipes = json.loads(sys.stdin.read())
    out, n = emit_lua(recipes)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    print("wrote %s: %d recipes" % (os.path.relpath(OUT, SCRIPT_DIR), n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
