#!/usr/bin/env python3
"""
Harvest quest/objective item drop data from QuestieDB into a bundled Lua data file for
DropChanceTooltip.

Why: LootDBLua (wowhead-derived) omits quest-only drops (items that only drop while on the quest),
e.g. Darksoul Shackle (3157) from Moonrage Darksoul (1782). QuestieDB's Forever drop table DOES
have them. We harvest that table once, ship it as data, and merge it into our mob-drop index at
runtime -- so there is NO runtime dependency on Questie.

Re-runnable: just run this again after QuestieDB updates. It regenerates the output file in place.
The generated file is committed so the addon works without Python.

Usage:
    python3 tools/harvest_questie_drops.py            # default paths (addon under Interface/AddOns)
    python3 tools/harvest_questie_drops.py --questiedb /path/to/QuestieDB --out Data/QuestieDrops.lua
"""
import argparse
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ADDON_DIR = os.path.dirname(SCRIPT_DIR)                 # AddOns/DropChanceTooltip
ADDONS_DIR = os.path.dirname(ADDON_DIR)                 # AddOns

# QuestieDB source tables to harvest, in order. Forever tables take priority (client match); the
# base classic table is a fallback for items the Forever table lacks. Both are item -> {npc -> pct}.
DEFAULT_SOURCES = [
    "support/Forever/DropTables/classicItemDrops.lua",
    "support/DropTables/classicItemDrops.lua",
]

# Matches a `wowheadData = [[ ... ]]` long-string block (the return-table payload).
LONGSTRING_RE = re.compile(r"wowheadData\s*=\s*\[\[(.*?)\]\]", re.S)
# One item block: `[itemID] = { ... }` (inner has no nested braces, so non-greedy to first `}`).
ITEM_RE = re.compile(r"\[(\d+)\]\s*=\s*\{(.*?)\}", re.S)
# One `[npcID] = rate` pair (rate is a percent, e.g. 46.8743).
PAIR_RE = re.compile(r"\[(\d+)\]\s*=\s*([0-9]+(?:\.[0-9]+)?)")


NAME_RE = re.compile(r"--\s*([^\n]+)")


def parse_drop_table(path):
    """Return (drops, names): { itemID: { npcID: pct } }, { itemID: "Name" }.
    The item name comes from the `-- Name` comment QuestieDB writes after `[itemID] = {`."""
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    m = LONGSTRING_RE.search(text)
    if not m:
        return {}, {}
    body = m.group(1)
    drops, names = {}, {}
    for item_m in ITEM_RE.finditer(body):
        item_id = int(item_m.group(1))
        inner = item_m.group(2)
        npcs = {}
        for pair_m in PAIR_RE.finditer(inner):
            npcs[int(pair_m.group(1))] = float(pair_m.group(2))
        if npcs:
            drops[item_id] = npcs
            nm = NAME_RE.search(inner)
            if nm:
                names[item_id] = nm.group(1).strip()
    return drops, names


def lua_quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--questiedb", default=os.path.join(ADDONS_DIR, "QuestieDB"),
                    help="Path to the QuestieDB addon folder")
    ap.add_argument("--out", default=os.path.join(ADDON_DIR, "Data", "QuestieDrops.lua"),
                    help="Output Lua data file")
    args = ap.parse_args()

    merged = {}          # itemID -> { npcID: pct }  (first source wins per item:npc)
    names = {}           # itemID -> "Name"
    used_sources = []
    for rel in DEFAULT_SOURCES:
        path = os.path.join(args.questiedb, rel)
        if not os.path.isfile(path):
            print(f"  skip (missing): {rel}")
            continue
        table, table_names = parse_drop_table(path)
        used_sources.append((rel, len(table)))
        for item_id, npcs in table.items():
            dst = merged.setdefault(item_id, {})
            for npc_id, pct in npcs.items():
                dst.setdefault(npc_id, pct)   # earlier source (Forever) wins
        for item_id, name in table_names.items():
            names.setdefault(item_id, name)
        print(f"  parsed {rel}: {len(table)} items")

    if not merged:
        print("ERROR: no data parsed -- check --questiedb path", file=sys.stderr)
        return 1

    item_count = len(merged)
    pair_count = sum(len(v) for v in merged.values())

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    lines = []
    lines.append("-- AUTO-GENERATED by tools/harvest_questie_drops.py -- DO NOT EDIT BY HAND.")
    lines.append("-- Source: QuestieDB Forever/base drop tables (quest-objective item drops that")
    lines.append("-- LootDBLua omits). Re-run the harvester after QuestieDB updates to regenerate.")
    lines.append(f"-- Items: {item_count}  item:npc pairs: {pair_count}  sources: "
                 + ", ".join(r for r, _ in used_sources))
    lines.append("-- Format: [itemID] = { [npcID] = dropPercent, ... }  (percent, e.g. 46.8743)")
    lines.append("DropChanceTooltip_QuestieDrops = {")
    for item_id in sorted(merged):
        npcs = merged[item_id]
        parts = ", ".join(f"[{npc}]={pct:g}" for npc, pct in sorted(npcs.items()))
        lines.append(f"    [{item_id}] = {{ {parts} }},")
    lines.append("}")
    lines.append("")
    lines.append("-- Item names (fallback when GetItemInfo can't resolve an uncached item).")
    lines.append("DropChanceTooltip_QuestieItemNames = {")
    for item_id in sorted(names):
        lines.append(f"    [{item_id}] = {lua_quote(names[item_id])},")
    lines.append("}")
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {args.out}: {item_count} items, {pair_count} item:npc pairs, {len(names)} names")
    print(f"  (sanity) 3157 -> {merged.get(3157)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
