#!/usr/bin/env python3
"""
Harvest classic NPC level ranges into a bundled table for DropChanceTooltip's material aggregation.

Cloth items show "Humanoids <min>-<max>" and leather items show "Skinning . Beasts <min>-<max>", where
the level range is computed from the SOURCE creatures: cloth sources come from LootDBLua at runtime,
leather sources from Data/SkinningSources.lua. Both resolve each creature's level here, in
Data/MobLevels.lua -> [npcId] = { minLevel, maxLevel, rank }.

Source: QuestieDB's classic NPC DB (plain Lua in the repo; the installed copy is packed). Field layout
(QuestieDB.npcKeys): 1=name, 4=minLevel, 5=maxLevel, 6=rank. Classic NPC levels are unchanged on Forever.

Usage:
    python3 tools/harvest_mob_levels.py                     # fetch classicNpcDB from the QuestieDB repo
    python3 tools/harvest_mob_levels.py --npcdb classicNpcDB.lua   # use a local copy
    python3 tools/harvest_mob_levels.py --selftest
"""
import argparse
import os
import re
import sys
import urllib.request

from forever_quest_npcs import LuaParser  # reuse the positional Lua-table parser

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCRIPT_DIR, "..", "Data", "MobLevels.lua")
RAW = "https://raw.githubusercontent.com/Questie/QuestieDB/master/data/Classic/classicNpcDB.lua"

NAME, MINLEVEL, MAXLEVEL, RANK = 1, 4, 5, 6


def load_npcdata(text):
    m = re.search(r"npcData\s*=\s*\[\[return\s*(\{.*\})\s*\]\]", text, re.S)
    if not m:
        raise ValueError("npcData [[return {...}]] block not found")
    return LuaParser(m.group(1)).parse()


def _int(v):
    return int(v) if isinstance(v, (int, float)) else 0


def build(npcdata):
    out = {}
    for nid, entry in npcdata.items():
        if not isinstance(entry, dict):
            continue
        mn, mx, rk = _int(entry.get(MINLEVEL)), _int(entry.get(MAXLEVEL)), _int(entry.get(RANK))
        if mn == 0 and mx == 0:
            continue  # unknown level -- useless for a range
        out[int(nid)] = (mn, mx, rk)
    return out


def emit_lua(levels):
    lines = [
        "-- AUTO-GENERATED by tools/harvest_mob_levels.py from QuestieDB classicNpcDB. DO NOT EDIT.",
        "-- [npcId] = { minLevel, maxLevel, rank }. Feeds cloth (Humanoids) + leather (Beasts) level",
        "-- ranges. Classic NPC levels are unchanged on Forever.",
        "DropChanceTooltip_MobLevels = {",
    ]
    for nid in sorted(levels):
        mn, mx, rk = levels[nid]
        if rk and rk != 0:
            lines.append("    [%d]={%d,%d,%d}," % (nid, mn, mx, rk))
        else:
            lines.append("    [%d]={%d,%d}," % (nid, mn, mx))
    lines.append("}")
    return "\n".join(lines) + "\n"


def read_source(local):
    if local:
        with open(local, "r", encoding="utf-8") as f:
            return f.read()
    print("  fetching %s" % RAW)
    req = urllib.request.Request(RAW, headers={"User-Agent": "DropChanceTooltip-tools"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read().decode("utf-8")


SAMPLE = r'''
QuestieDB.npcData = [[return {
[1] = {"Rabbit",0,1,1,1,0,{[1]={{1,2}}},nil,1,nil,nil,nil,nil,nil,nil},
[1132] = {"Snapjaw",0,1,25,26,0,{[1411]={{3,4}}},nil,1411,nil,nil,nil,nil,nil,nil},
[1133] = {"Elder Snapjaw",0,1,30,31,1,nil,nil,1411,nil,nil,nil,nil,nil,nil},
[9999] = {"Unknown Level Guy",0,1,0,0,0,nil,nil,1,nil,nil,nil,nil,nil,nil},
}]]
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npcdb", help="Local classicNpcDB.lua (default: fetch from the QuestieDB repo)")
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        levels = build(load_npcdata(SAMPLE))
        ok = levels.get(1132) == (25, 26, 0) and levels.get(1133) == (30, 31, 1) and 9999 not in levels
        print("levels: %s" % {k: levels[k] for k in sorted(levels)})
        print("PARSER OK" if ok else "PARSER FAILED")
        return 0 if ok else 1

    levels = build(load_npcdata(read_source(args.npcdb)))
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(emit_lua(levels))
    print("wrote %s: %d npcs with level ranges" % (os.path.relpath(args.out, SCRIPT_DIR), len(levels)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
